import type { Project, Meeting, Vote, User, AgendaItem, Notification, Workflow, WorkflowLog, ProjetoAnalytics, AtividadeMembro } from './types';

export const users: User[] = [
  { id: 'user-1', nome: 'Alice Johnson', full_name: 'Alice Johnson', email: 'alice@insight.com', avatarUrl: 'https://picsum.photos/seed/user1/40/40', papelPrincipal: 'admin', cargo: 'Chief Strategy Officer' },
  { id: 'user-2', nome: 'Robert Brown', full_name: 'Robert Brown', email: 'robert@insight.com', avatarUrl: 'https://picsum.photos/seed/user2/40/40', papelPrincipal: 'gerenteProjeto', cargo: 'Project Manager Lead' },
  { id: 'user-3', nome: 'Carlos Davis', full_name: 'Carlos Davis', email: 'carlos@insight.com', avatarUrl: 'https://picsum.photos/seed/user3/40/40', papelPrincipal: 'membroComite', cargo: 'Senior Engineer' },
  { id: 'user-4', nome: 'Diana Miller', full_name: 'Diana Miller', email: 'diana@insight.com', avatarUrl: 'https://picsum.photos/seed/user4/40/40', papelPrincipal: 'membroComite', cargo: 'Financial Analyst' },
  { id: 'user-5', nome: 'Edward Wilson', full_name: 'Edward Wilson', email: 'edward@insight.com', avatarUrl: 'https://picsum.photos/seed/user5/40/40', papelPrincipal: 'visualizador', cargo: 'Intern' },
];

export const projects: Project[] = [
  // ============================================
  // CEMIG S.A - R$ 198.827.691,78 (1 contrato)
  // ============================================
  { 
    id: 'proj-001', 
    nome: 'Modernização da Rede de Distribuição MG', 
    codigo: 'CEMIG-MOD-01', 
    cliente: 'CEMIG S.A',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'critico',
    valor_total: 198827691.78,
    valor_executado: 10353629.78,
    progresso_percentual: 5,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CEMIG-001',
    codigoInterno: 'CEMIG-MOD-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-06-01',
    created_date: '2024-06-01',
    descricao: 'Projeto de modernização e expansão da rede de distribuição de energia em Minas Gerais, incluindo smart grids e automação.',
    risco_geral: 'medio',
    roi_estimado: 22,
    tipo: 'transmissao',
  },

  // ============================================
  // PETROBRAS - R$ 188.922.698,70 (5 contratos)
  // ============================================
  { 
    id: 'proj-002', 
    nome: 'Plataforma Offshore P-80', 
    codigo: 'PETRO-P80-01', 
    cliente: 'PETROBRAS',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'critico',
    valor_total: 75569079.48,
    valor_executado: 22670723.84,
    progresso_percentual: 30,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-PETRO-001',
    codigoInterno: 'PETRO-P80-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-01-15',
    created_date: '2024-01-15',
    descricao: 'Instalação e comissionamento de sistemas elétricos na plataforma P-80 no pré-sal da Bacia de Santos.',
    risco_geral: 'alto',
    roi_estimado: 28,
    tipo: 'offshore',
  },
  { 
    id: 'proj-003', 
    nome: 'Refinaria REPAR - Expansão Elétrica', 
    codigo: 'PETRO-REPAR-02', 
    cliente: 'PETROBRAS',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'alto',
    valor_total: 45353847.66,
    valor_executado: 31747693.36,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-PETRO-002',
    codigoInterno: 'PETRO-REPAR-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-06-01',
    created_date: '2023-06-01',
    descricao: 'Expansão do sistema elétrico da refinaria REPAR para suportar novas unidades de processamento.',
    risco_geral: 'medio',
    roi_estimado: 24,
    tipo: 'industrial',
  },
  { 
    id: 'proj-004', 
    nome: 'Terminal GNL Bahia', 
    codigo: 'PETRO-GNL-03', 
    cliente: 'PETROBRAS',
    status: 'planejamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'revisao_pendente',
    responsavel: users[1], 
    impacto_financeiro: 'alto',
    valor_total: 37784539.74,
    valor_executado: 3778453.97,
    progresso_percentual: 10,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-PETRO-003',
    codigoInterno: 'PETRO-GNL-03',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-09-01',
    created_date: '2024-09-01',
    descricao: 'Projeto de infraestrutura elétrica para o novo terminal de GNL na Bahia.',
    risco_geral: 'medio',
    roi_estimado: 20,
    tipo: 'gas_natural',
  },
  { 
    id: 'proj-005', 
    nome: 'FPSO Almirante Barroso', 
    codigo: 'PETRO-FPSO-04', 
    cliente: 'PETROBRAS',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'alto',
    valor_total: 18892269.87,
    valor_executado: 15113815.90,
    progresso_percentual: 80,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-PETRO-004',
    codigoInterno: 'PETRO-FPSO-04',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-03-01',
    created_date: '2023-03-01',
    descricao: 'Sistemas de automação e controle elétrico para FPSO Almirante Barroso.',
    risco_geral: 'baixo',
    roi_estimado: 26,
    tipo: 'offshore',
  },
  { 
    id: 'proj-006', 
    nome: 'Dutos Terrestres - Manutenção Preventiva', 
    codigo: 'PETRO-DUT-05', 
    cliente: 'PETROBRAS',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 11322961.95,
    valor_executado: 11322961.95,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-PETRO-005',
    codigoInterno: 'PETRO-DUT-05',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-01-01',
    created_date: '2023-01-01',
    descricao: 'Manutenção preventiva e atualização de sistemas de proteção catódica em dutos terrestres.',
    risco_geral: 'baixo',
    roi_estimado: 18,
    tipo: 'industrial',
  },

  // ============================================
  // ENEL GREEN POWER - R$ 65.899.071,59 (6 contratos)
  // ============================================
  { 
    id: 'proj-007', 
    nome: 'Parque Eólico Serra das Vacas', 
    codigo: 'ENEL-EOL-01', 
    cliente: 'ENEL GREEN POWER',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'alto',
    valor_total: 21966357.20,
    valor_executado: 15376450.04,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEL-001',
    codigoInterno: 'ENEL-EOL-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2023-09-01',
    created_date: '2023-09-01',
    descricao: 'Implantação do parque eólico Serra das Vacas com capacidade de 200 MW em Pernambuco.',
    risco_geral: 'medio',
    roi_estimado: 25,
    tipo: 'eolica',
  },
  { 
    id: 'proj-008', 
    nome: 'Complexo Solar Apodi', 
    codigo: 'ENEL-SOL-02', 
    cliente: 'ENEL GREEN POWER',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'alto',
    valor_total: 16474767.90,
    valor_executado: 9884860.74,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEL-002',
    codigoInterno: 'ENEL-SOL-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-02-01',
    created_date: '2024-02-01',
    descricao: 'Expansão do complexo solar fotovoltaico Apodi no Ceará com mais 150 MW.',
    risco_geral: 'baixo',
    roi_estimado: 22,
    tipo: 'energia_solar',
  },
  { 
    id: 'proj-009', 
    nome: 'Subestação Eólica Lagoa dos Ventos II', 
    codigo: 'ENEL-SUB-03', 
    cliente: 'ENEL GREEN POWER',
    status: 'planejamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'revisao_pendente',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 10983178.60,
    valor_executado: 1098317.86,
    progresso_percentual: 10,
    sankhya_integrado: false,
    codigoInterno: 'ENEL-SUB-03',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2025-01-01',
    created_date: '2024-10-01',
    descricao: 'Construção de subestação de 500kV para expansão do parque Lagoa dos Ventos.',
    risco_geral: 'medio',
    roi_estimado: 20,
    tipo: 'transmissao',
  },
  { 
    id: 'proj-010', 
    nome: 'Repotenciação Parque Cristal', 
    codigo: 'ENEL-REP-04', 
    cliente: 'ENEL GREEN POWER',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 8237383.95,
    valor_executado: 8237383.95,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEL-004',
    codigoInterno: 'ENEL-REP-04',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-03-01',
    created_date: '2023-03-01',
    descricao: 'Repotenciação de aerogeradores do Parque Eólico Cristal na Bahia.',
    risco_geral: 'baixo',
    roi_estimado: 30,
    tipo: 'eolica',
  },
  { 
    id: 'proj-011', 
    nome: 'Sistema SCADA Nordeste', 
    codigo: 'ENEL-SCA-05', 
    cliente: 'ENEL GREEN POWER',
    status: 'em_andamento', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 5491589.30,
    valor_executado: 3844112.51,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEL-005',
    codigoInterno: 'ENEL-SCA-05',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2024-04-01',
    created_date: '2024-04-01',
    descricao: 'Implantação de sistema SCADA unificado para todos os parques do Nordeste.',
    risco_geral: 'baixo',
    roi_estimado: 35,
    tipo: 'automacao',
  },
  { 
    id: 'proj-012', 
    nome: 'Manutenção Preventiva Parques RN', 
    codigo: 'ENEL-MAN-06', 
    cliente: 'ENEL GREEN POWER',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 2745794.64,
    valor_executado: 1922056.25,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEL-006',
    codigoInterno: 'ENEL-MAN-06',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-01-01',
    created_date: '2024-01-01',
    descricao: 'Programa de manutenção preventiva para parques eólicos no Rio Grande do Norte.',
    risco_geral: 'baixo',
    roi_estimado: 18,
    tipo: 'eolica',
  },

  // ============================================
  // ELETROBRAS S.A - R$ 31.196.749,41 (4 contratos)
  // ============================================
  { 
    id: 'proj-013', 
    nome: 'Modernização UHE Tucuruí', 
    codigo: 'ELET-TUC-01', 
    cliente: 'ELETROBRAS S.A',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'alto',
    valor_total: 12478699.76,
    valor_executado: 7487219.86,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ELET-001',
    codigoInterno: 'ELET-TUC-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2023-08-01',
    created_date: '2023-08-01',
    descricao: 'Modernização dos sistemas de controle e proteção da UHE Tucuruí.',
    risco_geral: 'medio',
    roi_estimado: 20,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-014', 
    nome: 'LT 500kV Norte-Nordeste', 
    codigo: 'ELET-LT-02', 
    cliente: 'ELETROBRAS S.A',
    status: 'planejamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'atencao_necessaria',
    responsavel: users[1], 
    impacto_financeiro: 'alto',
    valor_total: 9359024.82,
    valor_executado: 935902.48,
    progresso_percentual: 10,
    sankhya_integrado: false,
    codigoInterno: 'ELET-LT-02',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2025-03-01',
    created_date: '2024-11-01',
    descricao: 'Nova linha de transmissão de 500kV interligando os subsistemas Norte e Nordeste.',
    risco_geral: 'alto',
    roi_estimado: 18,
    tipo: 'transmissao',
  },
  { 
    id: 'proj-015', 
    nome: 'SE Boa Vista - Expansão', 
    codigo: 'ELET-SE-03', 
    cliente: 'ELETROBRAS S.A',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 6239349.88,
    valor_executado: 4367544.92,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ELET-003',
    codigoInterno: 'ELET-SE-03',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-02-01',
    created_date: '2024-02-01',
    descricao: 'Expansão da subestação de Boa Vista em Roraima para atender crescimento de demanda.',
    risco_geral: 'medio',
    roi_estimado: 16,
    tipo: 'transmissao',
  },
  { 
    id: 'proj-016', 
    nome: 'Automação PCHs Região Sul', 
    codigo: 'ELET-PCH-04', 
    cliente: 'ELETROBRAS S.A',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 3119674.95,
    valor_executado: 3119674.95,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ELET-004',
    codigoInterno: 'ELET-PCH-04',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-01-01',
    created_date: '2023-01-01',
    descricao: 'Sistema de automação e monitoramento remoto para PCHs na região Sul.',
    risco_geral: 'baixo',
    roi_estimado: 25,
    tipo: 'hidreletrica',
  },

  // ============================================
  // ENEVA S.A - R$ 21.017.204,25 (4 contratos)
  // ============================================
  { 
    id: 'proj-017', 
    nome: 'UTE Parnaíba VI', 
    codigo: 'ENEV-PAR-01', 
    cliente: 'ENEVA S.A',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'alto',
    valor_total: 8406881.70,
    valor_executado: 5044129.02,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEV-001',
    codigoInterno: 'ENEV-PAR-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-03-01',
    created_date: '2024-03-01',
    descricao: 'Instalação elétrica da nova UTE Parnaíba VI no complexo termelétrico do Maranhão.',
    risco_geral: 'medio',
    roi_estimado: 22,
    tipo: 'termoeletrica',
  },
  { 
    id: 'proj-018', 
    nome: 'Exploração Gás Bacia do Parnaíba', 
    codigo: 'ENEV-GAS-02', 
    cliente: 'ENEVA S.A',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'alto',
    valor_total: 6305161.28,
    valor_executado: 3783096.77,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEV-002',
    codigoInterno: 'ENEV-GAS-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-01-01',
    created_date: '2024-01-01',
    descricao: 'Sistemas de controle e automação para campos de exploração de gás natural.',
    risco_geral: 'medio',
    roi_estimado: 28,
    tipo: 'gas_natural',
  },
  { 
    id: 'proj-019', 
    nome: 'UTE Jaguatirica II', 
    codigo: 'ENEV-JAG-03', 
    cliente: 'ENEVA S.A',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 4203440.85,
    valor_executado: 4203440.85,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEV-003',
    codigoInterno: 'ENEV-JAG-03',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-06-01',
    created_date: '2023-06-01',
    descricao: 'Comissionamento elétrico da UTE Jaguatirica II em Roraima.',
    risco_geral: 'baixo',
    roi_estimado: 20,
    tipo: 'termoeletrica',
  },
  { 
    id: 'proj-020', 
    nome: 'Manutenção Complexo Parnaíba', 
    codigo: 'ENEV-MAN-04', 
    cliente: 'ENEVA S.A',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 2101720.42,
    valor_executado: 1471204.29,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENEV-004',
    codigoInterno: 'ENEV-MAN-04',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-01-01',
    created_date: '2024-01-01',
    descricao: 'Contrato de manutenção e operação do complexo termelétrico Parnaíba.',
    risco_geral: 'baixo',
    roi_estimado: 15,
    tipo: 'termoeletrica',
  },

  // ============================================
  // ENERGIA PECEM - R$ 8.974.958,51 (2 contratos)
  // ============================================
  { 
    id: 'proj-021', 
    nome: 'UTE Pecém II - Retrofit', 
    codigo: 'PECEM-RET-01', 
    cliente: 'ENERGIA PECEM',
    status: 'planejamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'alto',
    valor_total: 5384975.11,
    valor_executado: 0,
    progresso_percentual: 0,
    sankhya_integrado: false,
    codigoInterno: 'PECEM-RET-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2025-03-01',
    created_date: '2024-12-01',
    descricao: 'Retrofit dos sistemas de proteção e controle da UTE Pecém II.',
    risco_geral: 'alto',
    roi_estimado: 18,
    tipo: 'termoeletrica',
  },
  { 
    id: 'proj-022', 
    nome: 'Sistema de Dessulfuração', 
    codigo: 'PECEM-DES-02', 
    cliente: 'ENERGIA PECEM',
    status: 'planejamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'revisao_pendente',
    responsavel: users[2], 
    impacto_financeiro: 'alto',
    valor_total: 3589983.40,
    valor_executado: 0,
    progresso_percentual: 0,
    sankhya_integrado: false,
    codigoInterno: 'PECEM-DES-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2025-06-01',
    created_date: '2024-12-15',
    descricao: 'Instalação de sistema de dessulfuração para adequação ambiental.',
    risco_geral: 'medio',
    roi_estimado: 12,
    tipo: 'ambiental',
  },

  // ============================================
  // HYDRO ALUNORTE - R$ 4.965.143,38 (1 contrato)
  // ============================================
  { 
    id: 'proj-023', 
    nome: 'Modernização Planta Alunorte', 
    codigo: 'HYDRO-ALU-01', 
    cliente: 'HYDRO ALUNORTE',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 4965143.38,
    valor_executado: 828439.34,
    progresso_percentual: 17,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-HYDRO-001',
    codigoInterno: 'HYDRO-ALU-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-08-01',
    created_date: '2024-08-01',
    descricao: 'Modernização do sistema elétrico da refinaria de alumina Alunorte no Pará.',
    risco_geral: 'medio',
    roi_estimado: 20,
    tipo: 'industrial',
  },

  // ============================================
  // FURNAS S.A - R$ 3.563.986,93 (1 contrato)
  // ============================================
  { 
    id: 'proj-024', 
    nome: 'SE Adrianópolis - Modernização', 
    codigo: 'FURN-ADR-01', 
    cliente: 'FURNAS S.A',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 3563986.93,
    valor_executado: 3563986.93,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-FURN-001',
    codigoInterno: 'FURN-ADR-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-01-01',
    created_date: '2023-01-01',
    descricao: 'Modernização completa da subestação de Adrianópolis no Rio de Janeiro.',
    risco_geral: 'baixo',
    roi_estimado: 22,
    tipo: 'transmissao',
  },

  // ============================================
  // CERAN/CPFL - R$ 2.755.977,06 (6 contratos)
  // ============================================
  { 
    id: 'proj-025', 
    nome: 'PCH Monte Claro', 
    codigo: 'CERAN-MC-01', 
    cliente: 'CERAN/ CPFL',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 688994.26,
    valor_executado: 688994.26,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CERAN-001',
    codigoInterno: 'CERAN-MC-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-04-01',
    created_date: '2023-04-01',
    descricao: 'Automação da PCH Monte Claro no Rio Grande do Sul.',
    risco_geral: 'baixo',
    roi_estimado: 18,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-026', 
    nome: 'PCH Castro Alves', 
    codigo: 'CERAN-CA-02', 
    cliente: 'CERAN/ CPFL',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 551195.41,
    valor_executado: 551195.41,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CERAN-002',
    codigoInterno: 'CERAN-CA-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-02-01',
    created_date: '2023-02-01',
    descricao: 'Manutenção e atualização de sistemas da PCH Castro Alves.',
    risco_geral: 'baixo',
    roi_estimado: 16,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-027', 
    nome: 'PCH 14 de Julho', 
    codigo: 'CERAN-14J-03', 
    cliente: 'CERAN/ CPFL',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 496075.87,
    valor_executado: 496075.87,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CERAN-003',
    codigoInterno: 'CERAN-14J-03',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-05-01',
    created_date: '2023-05-01',
    descricao: 'Retrofit de equipamentos de proteção da PCH 14 de Julho.',
    risco_geral: 'baixo',
    roi_estimado: 15,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-028', 
    nome: 'Sistema SCADA CERAN', 
    codigo: 'CERAN-SCA-04', 
    cliente: 'CERAN/ CPFL',
    status: 'concluido', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 413396.56,
    valor_executado: 413396.56,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CERAN-004',
    codigoInterno: 'CERAN-SCA-04',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2023-08-01',
    created_date: '2023-08-01',
    descricao: 'Implantação de sistema SCADA centralizado para todas as PCHs da CERAN.',
    risco_geral: 'baixo',
    roi_estimado: 25,
    tipo: 'automacao',
  },
  { 
    id: 'proj-029', 
    nome: 'Manutenção Preventiva PCHs', 
    codigo: 'CERAN-MAN-05', 
    cliente: 'CERAN/ CPFL',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 330717.25,
    valor_executado: 330717.25,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CERAN-005',
    codigoInterno: 'CERAN-MAN-05',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-01-01',
    created_date: '2023-01-01',
    descricao: 'Contrato anual de manutenção preventiva das PCHs da CERAN.',
    risco_geral: 'baixo',
    roi_estimado: 12,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-030', 
    nome: 'PCH Canastra', 
    codigo: 'CERAN-CAN-06', 
    cliente: 'CERAN/ CPFL',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 275597.71,
    valor_executado: 275597.71,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CERAN-006',
    codigoInterno: 'CERAN-CAN-06',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-06-01',
    created_date: '2023-06-01',
    descricao: 'Atualização de sistemas de medição da PCH Canastra.',
    risco_geral: 'baixo',
    roi_estimado: 14,
    tipo: 'hidreletrica',
  },

  // ============================================
  // GE VERNOVA - R$ 2.633.365,73 (3 contratos)
  // ============================================
  { 
    id: 'proj-031', 
    nome: 'Turbinas Eólicas - Manutenção', 
    codigo: 'GE-TUR-01', 
    cliente: 'GE VERNOVA',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 1316682.87,
    valor_executado: 921678.01,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-GE-001',
    codigoInterno: 'GE-TUR-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-02-01',
    created_date: '2024-02-01',
    descricao: 'Contrato de manutenção de turbinas eólicas GE instaladas no Nordeste.',
    risco_geral: 'baixo',
    roi_estimado: 18,
    tipo: 'eolica',
  },
  { 
    id: 'proj-032', 
    nome: 'Comissionamento Turbinas Cypress', 
    codigo: 'GE-CYP-02', 
    cliente: 'GE VERNOVA',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 790009.72,
    valor_executado: 790009.72,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-GE-002',
    codigoInterno: 'GE-CYP-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-07-01',
    created_date: '2023-07-01',
    descricao: 'Comissionamento de turbinas Cypress em novo parque eólico.',
    risco_geral: 'baixo',
    roi_estimado: 22,
    tipo: 'eolica',
  },
  { 
    id: 'proj-033', 
    nome: 'Treinamento Técnico GE', 
    codigo: 'GE-TRE-03', 
    cliente: 'GE VERNOVA',
    status: 'concluido', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 526673.14,
    valor_executado: 526673.14,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-GE-003',
    codigoInterno: 'GE-TRE-03',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2024-01-01',
    created_date: '2024-01-01',
    descricao: 'Programa de treinamento técnico para equipes de manutenção.',
    risco_geral: 'baixo',
    roi_estimado: 30,
    tipo: 'capacitacao',
  },

  // ============================================
  // ENGIE S.A - R$ 2.371.635,72 (2 contratos)
  // ============================================
  { 
    id: 'proj-034', 
    nome: 'Parque Solar Assú V', 
    codigo: 'ENGIE-SOL-01', 
    cliente: 'ENGIE S.A',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 1660145.00,
    valor_executado: 996087.00,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENGIE-001',
    codigoInterno: 'ENGIE-SOL-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-04-01',
    created_date: '2024-04-01',
    descricao: 'Instalação elétrica do novo parque solar Assú V no Rio Grande do Norte.',
    risco_geral: 'baixo',
    roi_estimado: 24,
    tipo: 'energia_solar',
  },
  { 
    id: 'proj-035', 
    nome: 'UHE Jirau - Manutenção', 
    codigo: 'ENGIE-JIR-02', 
    cliente: 'ENGIE S.A',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 711490.72,
    valor_executado: 497643.50,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-ENGIE-002',
    codigoInterno: 'ENGIE-JIR-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-01-01',
    created_date: '2024-01-01',
    descricao: 'Contrato de manutenção dos sistemas elétricos da UHE Jirau.',
    risco_geral: 'baixo',
    roi_estimado: 16,
    tipo: 'hidreletrica',
  },

  // ============================================
  // BELÉM BIOENERGIA - R$ 2.085.276,19 (3 contratos)
  // ============================================
  { 
    id: 'proj-036', 
    nome: 'Usina de Biodiesel Belém', 
    codigo: 'BIO-BEL-01', 
    cliente: 'BELÉM BIOENERGIA',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 1042638.10,
    valor_executado: 625582.86,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-BIO-001',
    codigoInterno: 'BIO-BEL-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-05-01',
    created_date: '2024-05-01',
    descricao: 'Instalação elétrica da usina de biodiesel de palma em Belém.',
    risco_geral: 'medio',
    roi_estimado: 20,
    tipo: 'biomassa',
  },
  { 
    id: 'proj-037', 
    nome: 'Sistema de Cogeração', 
    codigo: 'BIO-COG-02', 
    cliente: 'BELÉM BIOENERGIA',
    status: 'planejamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'revisao_pendente',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 625582.86,
    valor_executado: 62558.29,
    progresso_percentual: 10,
    sankhya_integrado: false,
    codigoInterno: 'BIO-COG-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2025-02-01',
    created_date: '2024-11-01',
    descricao: 'Sistema de cogeração de energia a partir de biomassa.',
    risco_geral: 'medio',
    roi_estimado: 25,
    tipo: 'biomassa',
  },
  { 
    id: 'proj-038', 
    nome: 'Automação Linha de Produção', 
    codigo: 'BIO-AUT-03', 
    cliente: 'BELÉM BIOENERGIA',
    status: 'em_andamento', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 417055.23,
    valor_executado: 291938.66,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-BIO-003',
    codigoInterno: 'BIO-AUT-03',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2024-03-01',
    created_date: '2024-03-01',
    descricao: 'Automação da linha de produção de biodiesel.',
    risco_geral: 'baixo',
    roi_estimado: 28,
    tipo: 'automacao',
  },

  // ============================================
  // ÂMBAR ENERGIA - R$ 1.758.120,89 (2 contratos)
  // ============================================
  { 
    id: 'proj-039', 
    nome: 'UTE Cuiabá - Retrofit', 
    codigo: 'AMBAR-CUI-01', 
    cliente: 'ÂMBAR ENERGIA',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'medio',
    valor_total: 1054872.53,
    valor_executado: 632923.52,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-AMBAR-001',
    codigoInterno: 'AMBAR-CUI-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-06-01',
    created_date: '2024-06-01',
    descricao: 'Retrofit dos sistemas de controle da UTE Cuiabá.',
    risco_geral: 'medio',
    roi_estimado: 18,
    tipo: 'termoeletrica',
  },
  { 
    id: 'proj-040', 
    nome: 'Sistema de Monitoramento', 
    codigo: 'AMBAR-MON-02', 
    cliente: 'ÂMBAR ENERGIA',
    status: 'em_andamento', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 703248.36,
    valor_executado: 492073.85,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-AMBAR-002',
    codigoInterno: 'AMBAR-MON-02',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2024-04-01',
    created_date: '2024-04-01',
    descricao: 'Sistema de monitoramento preditivo para UTEs.',
    risco_geral: 'baixo',
    roi_estimado: 32,
    tipo: 'automacao',
  },

  // ============================================
  // POWER BUS - R$ 1.368.159,75 (1 contrato)
  // ============================================
  { 
    id: 'proj-041', 
    nome: 'Fabricação de Barramentos', 
    codigo: 'PWBUS-FAB-01', 
    cliente: 'POWER BUS',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'medio',
    valor_total: 1368159.75,
    valor_executado: 1368159.75,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-PWBUS-001',
    codigoInterno: 'PWBUS-FAB-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-09-01',
    created_date: '2023-09-01',
    descricao: 'Fornecimento de barramentos blindados para subestações.',
    risco_geral: 'baixo',
    roi_estimado: 20,
    tipo: 'industrial',
  },

  // ============================================
  // SINOP ENERGIA - R$ 1.053.612,00 (3 contratos)
  // ============================================
  { 
    id: 'proj-042', 
    nome: 'UHE Sinop - Manutenção', 
    codigo: 'SINOP-MAN-01', 
    cliente: 'SINOP ENERGIA',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 526806.00,
    valor_executado: 368764.20,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-SINOP-001',
    codigoInterno: 'SINOP-MAN-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-01-01',
    created_date: '2024-01-01',
    descricao: 'Contrato de manutenção da UHE Sinop no Mato Grosso.',
    risco_geral: 'baixo',
    roi_estimado: 15,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-043', 
    nome: 'Modernização Vertedouros', 
    codigo: 'SINOP-VER-02', 
    cliente: 'SINOP ENERGIA',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 316083.60,
    valor_executado: 316083.60,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-SINOP-002',
    codigoInterno: 'SINOP-VER-02',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-08-01',
    created_date: '2023-08-01',
    descricao: 'Modernização dos sistemas de controle dos vertedouros.',
    risco_geral: 'baixo',
    roi_estimado: 18,
    tipo: 'hidreletrica',
  },
  { 
    id: 'proj-044', 
    nome: 'Segurança de Barragem', 
    codigo: 'SINOP-SEG-03', 
    cliente: 'SINOP ENERGIA',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'atencao_necessaria',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 210722.40,
    valor_executado: 147505.68,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-SINOP-003',
    codigoInterno: 'SINOP-SEG-03',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-05-01',
    created_date: '2024-05-01',
    descricao: 'Sistemas de instrumentação para segurança de barragem.',
    risco_geral: 'medio',
    roi_estimado: 12,
    tipo: 'seguranca',
  },

  // ============================================
  // KLABIN S.A - R$ 950.000,00 (1 contrato)
  // ============================================
  { 
    id: 'proj-045', 
    nome: 'Cogeração Puma II', 
    codigo: 'KLAB-PUM-01', 
    cliente: 'KLABIN S.A',
    status: 'em_andamento', 
    comite_id: 'com-1',
    comite_nome: 'Comitê Estratégico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 950000.00,
    valor_executado: 285000.00,
    progresso_percentual: 30,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-KLAB-001',
    codigoInterno: 'KLAB-PUM-01',
    comiteResponsavel: 'Comitê Estratégico',
    data_inicio: '2024-07-01',
    created_date: '2024-07-01',
    descricao: 'Sistema elétrico para planta de cogeração Puma II no Paraná.',
    risco_geral: 'medio',
    roi_estimado: 22,
    tipo: 'biomassa',
  },

  // ============================================
  // CELESC S.A - R$ 716.474,54 (2 contratos)
  // ============================================
  { 
    id: 'proj-046', 
    nome: 'Modernização SE Blumenau', 
    codigo: 'CELESC-BLU-01', 
    cliente: 'CELESC S.A',
    status: 'em_andamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 430084.72,
    valor_executado: 258050.83,
    progresso_percentual: 60,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CELESC-001',
    codigoInterno: 'CELESC-BLU-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2024-04-01',
    created_date: '2024-04-01',
    descricao: 'Modernização da subestação de Blumenau em Santa Catarina.',
    risco_geral: 'baixo',
    roi_estimado: 18,
    tipo: 'transmissao',
  },
  { 
    id: 'proj-047', 
    nome: 'Automação Rede MT', 
    codigo: 'CELESC-AUT-02', 
    cliente: 'CELESC S.A',
    status: 'em_andamento', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 286389.82,
    valor_executado: 200472.87,
    progresso_percentual: 70,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-CELESC-002',
    codigoInterno: 'CELESC-AUT-02',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2024-02-01',
    created_date: '2024-02-01',
    descricao: 'Automação da rede de média tensão na região de Florianópolis.',
    risco_geral: 'baixo',
    roi_estimado: 25,
    tipo: 'automacao',
  },

  // ============================================
  // ARCELOR MITTAL - R$ 476.716,69 (2 contratos)
  // ============================================
  { 
    id: 'proj-048', 
    nome: 'Siderúrgica Tubarão - Elétrica', 
    codigo: 'ARCEL-TUB-01', 
    cliente: 'ARCELOR MITTAL',
    status: 'planejamento', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'revisao_pendente',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 286030.01,
    valor_executado: 0,
    progresso_percentual: 0,
    sankhya_integrado: false,
    codigoInterno: 'ARCEL-TUB-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2025-04-01',
    created_date: '2024-12-01',
    descricao: 'Modernização elétrica da siderúrgica de Tubarão no Espírito Santo.',
    risco_geral: 'medio',
    roi_estimado: 16,
    tipo: 'industrial',
  },
  { 
    id: 'proj-049', 
    nome: 'Monlevade - Automação', 
    codigo: 'ARCEL-MON-02', 
    cliente: 'ARCELOR MITTAL',
    status: 'planejamento', 
    comite_id: 'com-3',
    comite_nome: 'Comitê de Inovação',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 190686.68,
    valor_executado: 0,
    progresso_percentual: 0,
    sankhya_integrado: false,
    codigoInterno: 'ARCEL-MON-02',
    comiteResponsavel: 'Comitê de Inovação',
    data_inicio: '2025-05-01',
    created_date: '2024-12-15',
    descricao: 'Sistema de automação para a planta de Monlevade.',
    risco_geral: 'baixo',
    roi_estimado: 22,
    tipo: 'automacao',
  },

  // ============================================
  // BRASKEM S.A - R$ 411.525,00 (1 contrato)
  // ============================================
  { 
    id: 'proj-050', 
    nome: 'Petroquímica Camaçari', 
    codigo: 'BRASK-CAM-01', 
    cliente: 'BRASKEM S.A',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 411525.00,
    valor_executado: 411525.00,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-BRASK-001',
    codigoInterno: 'BRASK-CAM-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-10-01',
    created_date: '2023-10-01',
    descricao: 'Manutenção de sistemas elétricos no polo petroquímico de Camaçari.',
    risco_geral: 'baixo',
    roi_estimado: 15,
    tipo: 'industrial',
  },

  // ============================================
  // TIJOÁ - R$ 379.220,83 (1 contrato)
  // ============================================
  { 
    id: 'proj-051', 
    nome: 'UHE Cachoeira do Caí', 
    codigo: 'TIJOA-CAC-01', 
    cliente: 'TIJOÁ',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[2], 
    impacto_financeiro: 'baixo',
    valor_total: 379220.83,
    valor_executado: 379220.83,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-TIJOA-001',
    codigoInterno: 'TIJOA-CAC-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-11-01',
    created_date: '2023-11-01',
    descricao: 'Manutenção de sistemas da UHE Cachoeira do Caí.',
    risco_geral: 'baixo',
    roi_estimado: 14,
    tipo: 'hidreletrica',
  },

  // ============================================
  // COPEL S.A - R$ 137.944,80 (1 contrato)
  // ============================================
  { 
    id: 'proj-052', 
    nome: 'Consultoria Técnica COPEL', 
    codigo: 'COPEL-CON-01', 
    cliente: 'COPEL S.A',
    status: 'concluido', 
    comite_id: 'com-2',
    comite_nome: 'Comitê Técnico',
    comite_status: 'ativo',
    responsavel: users[1], 
    impacto_financeiro: 'baixo',
    valor_total: 137944.80,
    valor_executado: 137944.80,
    progresso_percentual: 100,
    sankhya_integrado: true,
    sankhya_projeto_id: 'SK-COPEL-001',
    codigoInterno: 'COPEL-CON-01',
    comiteResponsavel: 'Comitê Técnico',
    data_inicio: '2023-12-01',
    created_date: '2023-12-01',
    descricao: 'Consultoria técnica para projetos de modernização de subestações.',
    risco_geral: 'baixo',
    roi_estimado: 40,
    tipo: 'consultoria',
  },
];

export const meetings: Meeting[] = [
  { id: 'meet-01', titulo: 'Revisão Trimestral de Projetos', comite: 'Comitê Estratégico', dataHoraInicio: '2024-08-25T14:00:00', tipoReuniao: 'ordinaria', status: 'agendada', participantes: users.slice(0, 3).map(u => u.email), participantes_nomes: users.slice(0,3).map(u=>u.nome) },
  { id: 'meet-02', titulo: 'Análise de Viabilidade - Projeto HIB-NEW-01', comite: 'Comitê Técnico', dataHoraInicio: '2024-09-05T10:00:00', tipoReuniao: 'extraordinaria', status: 'agendada', participantes: users.slice(1, 4).map(u => u.email), participantes_nomes: users.slice(1,4).map(u=>u.nome) },
  { id: 'meet-03', titulo: 'Planejamento de P&D para 2025', comite: 'Comitê de Inovação', dataHoraInicio: '2024-07-20T09:30:00', tipoReuniao: 'ordinaria', status: 'encerrada', participantes: users.slice(2, 5).map(u => u.email), participantes_nomes: users.slice(2,5).map(u=>u.nome) },
];

export const votes: Vote[] = [
  { id: 'vote-01', titulo: 'Aprovação do CAPEX para SOL-EXP-01', comite: 'Comitê Estratégico', status: 'encerrada', prazoFim: new Date('2024-07-28T23:59:59').toISOString() },
  { id: 'vote-02', titulo: 'Eleição do Presidente do Comitê Técnico', comite: 'Comitê Técnico', status: 'em_andamento', prazoFim: new Date('2024-08-30T23:59:59').toISOString() },
  { id: 'vote-03', titulo: 'Priorização de projetos de P&D', comite: 'Comitê de Inovação', status: 'nao_iniciada', prazoFim: new Date('2024-09-15T23:59:59').toISOString() },
];

export const agendaItems: AgendaItem[] = [
    { id: 'pauta-1', titulo: 'Revisão do Orçamento do Projeto X', descricao: 'Analisar o desvio orçamentário e aprovar novo CAPEX.', responsavel: users[1], status: 'deliberada' },
    { id: 'pauta-2', titulo: 'Apresentação de Novos Fornecedores', descricao: 'Avaliar propostas de fornecedores para a expansão da planta.', responsavel: users[2], status: 'em_discussao' },
    { id: 'pauta-3', titulo: 'Discussão sobre Cronograma', descricao: 'Definir as próximas milestones do projeto.', responsavel: users[1], status: 'pendente' },
];

export const notifications: Notification[] = [
    {
      id: 'notif-1',
      usuario_email: 'alice@insight.com',
      titulo: 'Reunião em 30 minutos',
      mensagem: 'Sua reunião "Revisão Trimestral de Projetos" começará em breve.',
      lida: false,
      tipo: 'reuniao_proxima',
      link: '/reunioes/meet-01',
      cor: '#FF7A3D', // orange
      created_date: '2024-08-25T13:30:00Z',
    },
    {
      id: 'notif-2',
      usuario_email: 'alice@insight.com',
      titulo: 'Nova pauta para votação',
      mensagem: 'A pauta "Priorização de projetos de P&D" foi aberta para votação.',
      lida: false,
      tipo: 'nova_pauta',
      link: '/votacoes/vote-03',
      cor: '#3B82F6', // blue
      created_date: '2024-08-24T10:00:00Z',
    },
    {
      id: 'notif-3',
      usuario_email: 'alice@insight.com',
      titulo: 'Votação encerrada',
      mensagem: 'A votação para "Aprovação do CAPEX para SOL-EXP-01" foi encerrada.',
      lida: true,
      tipo: 'votacao_encerrada',
      link: '/votacoes/vote-01',
      cor: '#008751', // green
      created_date: '2024-07-29T00:05:00Z',
    },
    {
      id: 'notif-4',
      usuario_email: 'alice@insight.com',
      titulo: 'Você foi adicionado a um comitê',
      mensagem: 'Robert Brown adicionou você ao "Comitê Estratégico".',
      lida: true,
      tipo: 'membro_adicionado',
      link: '/comites/proj-001',
      cor: '#8B5CF6', // purple
      created_date: '2024-07-15T11:00:00Z',
    },
];

export const pautas = votes.map(vote => ({
  comite_id: 'com-1',
  sankhya_projeto_id: 'SK-123',
  ...vote
}));

export const globalRoles = [
  {
    id: 'role-global-1',
    nome: 'Super Admin',
    descricao: 'Acesso total a todas as funcionalidades do sistema.',
    tipo: 'admin',
    nivel_acesso: 10,
    cor: '#D946EF',
    is_system_role: true,
    permissoes: Object.fromEntries(
      [
        'projetos_visualizar', 'projetos_criar', 'projetos_editar', 'projetos_deletar',
        'comites_visualizar', 'comites_criar', 'comites_editar', 'comites_deletar',
        'pautas_visualizar', 'pautas_criar', 'pautas_editar', 'pautas_deletar', 'pautas_votar', 'pautas_iniciar_votacao',
        'reunioes_visualizar', 'reunioes_criar', 'reunioes_editar', 'reunioes_deletar', 'reunioes_ata',
        'membros_visualizar', 'membros_gerenciar',
        'relatorios_visualizar', 'relatorios_exportar', 'relatorios_avancados',
        'financeiro_visualizar', 'financeiro_editar',
        'sistema_configuracoes', 'sistema_usuarios', 'sistema_roles'
      ].map(key => [key, true])
    ),
  },
  {
    id: 'role-global-2',
    nome: 'Gerente de Projetos',
    descricao: 'Gerencia projetos, mas não tem acesso a configurações de sistema.',
    tipo: 'project_manager',
    nivel_acesso: 7,
    cor: '#3B82F6',
    is_system_role: false,
    permissoes: {
      projetos_visualizar: true,
      projetos_criar: true,
      projetos_editar: true,
      comites_visualizar: true,
      pautas_visualizar: true,
      pautas_criar: true,
      pautas_votar: true,
      reunioes_visualizar: true,
      reunioes_criar: true,
      membros_visualizar: true,
      relatorios_visualizar: true,
    },
  },
  {
    id: 'role-global-3',
    nome: 'Membro de Comitê',
    descricao: 'Participa de comitês, vota em pautas e participa de reuniões.',
    tipo: 'committee_member',
    nivel_acesso: 5,
    cor: '#22C55E',
    is_system_role: false,
    permissoes: {
      comites_visualizar: true,
      pautas_visualizar: true,
      pautas_votar: true,
      reunioes_visualizar: true,
    },
  },
    {
    id: 'role-global-4',
    nome: 'Visualizador',
    descricao: 'Acesso somente leitura a relatórios e dashboards.',
    tipo: 'viewer',
    nivel_acesso: 2,
    cor: '#64748B',
    is_system_role: false,
    permissoes: {
      projetos_visualizar: true,
      comites_visualizar: true,
      pautas_visualizar: true,
      reunioes_visualizar: true,
      relatorios_visualizar: true,
    },
  },
];

export const workflows: Workflow[] = [
  { id: 'wf-1', nome: 'Notificar prazo de votação', descricao: 'Envia email 24h antes do prazo final da votação.', tipo: 'lembrete_votacao', ativa: true, prioridade: 8, frequencia_execucao: 'diaria', total_execucoes: 152, created_date: '2024-01-15T10:00:00Z' },
  { id: 'wf-2', nome: 'Atribuir tarefa após reunião', descricao: 'Cria tarefas para responsáveis após a publicação da ata.', tipo: 'atribuicao_tarefa', ativa: true, prioridade: 7, frequencia_execucao: 'imediata', total_execucoes: 34, created_date: '2024-02-20T10:00:00Z' },
  { id: 'wf-3', nome: 'Alerta de Risco em Projeto', descricao: 'Notifica comitê supervisor quando um projeto é marcado com risco alto.', tipo: 'alerta_risco', ativa: false, prioridade: 10, frequencia_execucao: 'imediata', total_execucoes: 5, created_date: '2024-03-10T10:00:00Z' },
  { id: 'wf-4', nome: 'Aprovação de Orçamento', descricao: 'Inicia pauta de votação para orçamentos acima de 50k.', tipo: 'aprovacao_orcamento', ativa: true, prioridade: 9, frequencia_execucao: 'imediata', total_execucoes: 12, created_date: '2024-04-05T10:00:00Z' },
];

export const workflowLogs: WorkflowLog[] = [
  { id: 'log-1', workflow_id: 'wf-1', status: 'success', trigger_evento: 'Votação vote-02 se aproximando do prazo', duracao_ms: 150, created_date: '2024-08-29T23:59:59Z' },
  { id: 'log-2', workflow_id: 'wf-2', status: 'success', trigger_evento: 'Ata da reunião meet-03 publicada', duracao_ms: 250, created_date: '2024-07-20T11:30:00Z' },
  { id: 'log-3', workflow_id: 'wf-4', status: 'failed', trigger_evento: 'Solicitação de orçamento de 75k para proj-001', erro_mensagem: 'API do sistema financeiro indisponível', duracao_ms: 5000, created_date: '2024-08-28T15:00:00Z' },
  { id: 'log-4', workflow_id: 'wf-1', status: 'success', trigger_evento: 'Votação vote-01 se aproximando do prazo', duracao_ms: 140, created_date: '2024-07-27T23:59:59Z' },
];

export const mockAnalytics: ProjetoAnalytics = {
  id: 'analytics-1',
  projeto_id: 'proj-001',
  projeto_nome: 'Expansão da Planta Solar',
  data_analise: '2024-08-30',
  score_saude_projeto: 78,
  ia_insights: 'O projeto está no caminho certo, mas o risco orçamentário aumentou devido à flutuação de preços de matéria-prima. Recomenda-se renegociar com fornecedores e revisar a alocação de recursos para contingência.',
  avaliacao_risco: {
    nivel_risco: 'medio',
    score_risco: 65,
    fatores_risco: [
      { fator: 'Orçamentário', impacto: 'alto', descricao: 'Volatilidade nos preços de painéis solares.', mitigacao_sugerida: 'Contratos de longo prazo com fornecedores.' },
      { fator: 'Cronograma', impacto: 'medio', descricao: 'Possíveis atrasos na entrega de equipamentos.', mitigacao_sugerida: 'Monitoramento semanal e fornecedores alternativos.' }
    ],
    riscos_identificados: ['Volatilidade de Preços', 'Atraso na Logística']
  },
  previsao_roi: {
    roi_estimado_percentual: 18,
    roi_pessimista: 12,
    roi_realista: 18,
    roi_otimista: 25,
    payback_meses: 48,
    valor_presente_liquido: 2500000,
    taxa_retorno_interna: 15
  },
  alocacao_recursos: {
    eficiencia_alocacao: 85,
    custo_total_recursos: 450000,
    recursos_humanos: [
      { role: 'Gerente de Projeto', horas_alocadas: 160, custo_estimado: 30000, utilizacao_percentual: 95 },
      { role: 'Engenheiro Elétrico Sênior', horas_alocadas: 200, custo_estimado: 45000, utilizacao_percentual: 110 },
      { role: 'Analista Financeiro', horas_alocadas: 80, custo_estimado: 15000, utilizacao_percentual: 70 }
    ],
    recursos_materiais: [
      { item: 'Painéis Solares (lote)', quantidade: 5000, custo: 250000 },
      { item: 'Inversores', quantidade: 100, custo: 75000 }
    ],
    recursos_subutilizados: ['Analista Financeiro'],
    recursos_sobreutilizados: ['Engenheiro Elétrico Sênior']
  },
  recomendacoes: [
    { tipo: 'financeiro', prioridade: 'alta', descricao: 'Renegociar contrato com fornecedor de painéis solares para fixar preços.', impacto_esperado: 'Redução de até 10% no CAPEX.' },
    { tipo: 'operacional', prioridade: 'media', descricao: 'Alocar um engenheiro de projeto adicional para supervisionar a logística.', impacto_esperado: 'Mitigação de atrasos no cronograma.' }
  ]
};

export const atividadesMembro: AtividadeMembro[] = [
    {
      id: 'act-1',
      usuario_email: 'carlos@insight.com',
      usuario_nome: 'Carlos Davis',
      tipo_atividade: 'voto',
      descricao: 'Votou a favor na pauta "Aprovação do CAPEX para SOL-EXP-01"',
      comite_nome: 'Comitê Estratégico',
      created_date: '2024-07-27T10:00:00Z',
    },
    {
      id: 'act-2',
      usuario_email: 'robert@insight.com',
      usuario_nome: 'Robert Brown',
      tipo_atividade: 'pauta_criada',
      descricao: 'Criou a pauta "Eleição do Presidente do Comitê Técnico"',
      comite_nome: 'Comitê Técnico',
      created_date: '2024-08-20T15:30:00Z',
    },
    {
      id: 'act-3',
      usuario_email: 'alice@insight.com',
      usuario_nome: 'Alice Johnson',
      tipo_atividade: 'reuniao_participada',
      descricao: 'Participou da reunião "Planejamento de P&D para 2025"',
      comite_nome: 'Comitê de Inovação',
      created_date: '2024-07-20T09:30:00Z',
    },
    {
      id: 'act-4',
      usuario_email: 'diana@insight.com',
      usuario_nome: 'Diana Miller',
      tipo_atividade: 'comentario',
      descricao: 'Adicionou um comentário na pauta "Priorização de projetos de P&D"',
      comite_nome: 'Comitê de Inovação',
      created_date: '2024-08-25T11:00:00Z',
    },
];

    