'use client';

import { useState } from "react";
import { Contract, Risk } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { 
  Upload, 
  FileText, 
  Sparkles, 
  Calendar,
  DollarSign,
  AlertTriangle,
  CheckCircle,
  Loader2
} from "lucide-react";
import { format, differenceInDays, addDays } from "date-fns";
import { pt } from "date-fns/locale";

interface ContractUploadProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onContractCreated: (contract: Contract, autoGeneratedRisk?: Risk) => void;
}

export function ContractUpload({ open, onOpenChange, onContractCreated }: ContractUploadProps) {
  const [file, setFile] = useState<File | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [aiResult, setAiResult] = useState<Partial<Contract> | null>(null);
  const [progress, setProgress] = useState(0);

  // Mock AI extraction
  const simulateAIExtraction = async (file: File): Promise<Partial<Contract>> => {
    // Simulate progressive analysis
    setProgress(0);
    await new Promise(resolve => setTimeout(resolve, 300));
    setProgress(25);
    
    await new Promise(resolve => setTimeout(resolve, 400));
    setProgress(50);
    
    await new Promise(resolve => setTimeout(resolve, 500));
    setProgress(75);
    
    await new Promise(resolve => setTimeout(resolve, 400));
    setProgress(100);

    // Mock extracted data
    const mockData = {
      name: file.name.replace(/\.[^/.]+$/, ""),
      vendorOrParty: 'Fornecedor Exemplo LTDA',
      value: Math.random() * 1000000 + 100000,
      currency: 'BRL',
      signingDate: new Date(),
      expirationDate: addDays(new Date(), Math.floor(Math.random() * 730) + 180), // 6 months to 2 years
      fileUrl: URL.createObjectURL(file),
    };

    // Calculate risk classification
    const daysUntilExpiration = differenceInDays(mockData.expirationDate!, new Date());
    const isHighValue = mockData.value! > 500000;
    const isExpiringSoon = daysUntilExpiration < 90;

    let riskClassification: 'low' | 'medium' | 'high';
    let status: 'active' | 'expiring_soon' | 'expired';

    if (daysUntilExpiration < 0) {
      status = 'expired';
      riskClassification = 'high';
    } else if (daysUntilExpiration < 30) {
      status = 'expiring_soon';
      riskClassification = isHighValue ? 'high' : 'medium';
    } else {
      status = 'active';
      riskClassification = (isHighValue && isExpiringSoon) ? 'high' : isExpiringSoon ? 'medium' : 'low';
    }

    return {
      ...mockData,
      riskClassification,
      status,
    };
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setAiResult(null);
      setProgress(0);
    }
  };

  const handleAnalyze = async () => {
    if (!file) return;

    setAnalyzing(true);
    try {
      const result = await simulateAIExtraction(file);
      setAiResult(result);
    } catch (error) {
      console.error('AI extraction failed:', error);
    } finally {
      setAnalyzing(false);
    }
  };

  const handleSave = () => {
    if (!aiResult) return;

    const newContract: Contract = {
      id: `contract-${Date.now()}`,
      name: aiResult.name!,
      vendorOrParty: aiResult.vendorOrParty!,
      value: aiResult.value!,
      currency: aiResult.currency!,
      signingDate: aiResult.signingDate,
      expirationDate: aiResult.expirationDate,
      fileUrl: aiResult.fileUrl!,
      riskClassification: aiResult.riskClassification!,
      status: aiResult.status!,
      uploadedAt: new Date(),
    };

    // Auto-create risk if high classification
    let autoGeneratedRisk: Risk | undefined;
    if (aiResult.riskClassification === 'high') {
      const daysUntilExpiration = differenceInDays(aiResult.expirationDate!, new Date());
      
      autoGeneratedRisk = {
        id: `risk-${Date.now()}`,
        title: `Risco Contratual – ${aiResult.name}`,
        description: `Contrato de alto valor (${new Intl.NumberFormat('pt-BR', { 
          style: 'currency', 
          currency: 'BRL' 
        }).format(aiResult.value!)}) ${daysUntilExpiration < 30 ? 'com expiração iminente' : 'requer monitoramento'}`,
        category: 'Contractual',
        probability: 4,
        impact: 4,
        level: 16,
        severity: 'critical',
        origin: 'contract',
        referenceId: newContract.id,
        status: 'open',
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    }

    onContractCreated(newContract, autoGeneratedRisk);
    handleClose();
  };

  const handleClose = () => {
    setFile(null);
    setAiResult(null);
    setAnalyzing(false);
    setProgress(0);
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Upload className="w-5 h-5 text-emerald-600" />
            Upload e Análise de Contrato
          </DialogTitle>
          <DialogDescription>
            Faça upload do contrato para análise automática com IA
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* File Upload */}
          <div className="space-y-2">
            <Label htmlFor="file">Arquivo do Contrato</Label>
            <Input
              id="file"
              type="file"
              accept=".pdf,.doc,.docx"
              onChange={handleFileChange}
            />
            <p className="text-xs text-slate-500">
              Formatos aceitos: PDF, DOC, DOCX (máx. 50MB)
            </p>
          </div>

          {/* Analyze Button */}
          {file && !aiResult && (
            <Button
              onClick={handleAnalyze}
              disabled={analyzing}
              className="w-full bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700"
            >
              {analyzing ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Analisando com IA...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Analisar com IA
                </>
              )}
            </Button>
          )}

          {/* Progress Bar */}
          {analyzing && (
            <div className="space-y-2">
              <Progress value={progress} className="h-2" />
              <p className="text-sm text-center text-slate-600">
                {progress < 30 && 'Lendo documento...'}
                {progress >= 30 && progress < 60 && 'Extraindo datas...'}
                {progress >= 60 && progress < 90 && 'Classificando risco...'}
                {progress >= 90 && 'Finalizando análise...'}
              </p>
            </div>
          )}

          {/* AI Results */}
          {aiResult && (
            <Card className="p-4 border-2 border-emerald-200 bg-emerald-50/30 space-y-4">
              <div className="flex items-center gap-2 text-emerald-700 font-semibold">
                <CheckCircle className="w-5 h-5" />
                Análise Concluída
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-xs text-slate-600">Nome do Contrato</Label>
                  <p className="font-medium text-slate-900">{aiResult.name}</p>
                </div>
                <div>
                  <Label className="text-xs text-slate-600">Fornecedor</Label>
                  <p className="font-medium text-slate-900">{aiResult.vendorOrParty}</p>
                </div>
                <div>
                  <Label className="text-xs text-slate-600">Valor</Label>
                  <p className="font-medium text-slate-900 flex items-center gap-1">
                    <DollarSign className="w-4 h-4" />
                    {new Intl.NumberFormat('pt-BR', { 
                      style: 'currency', 
                      currency: 'BRL' 
                    }).format(aiResult.value!)}
                  </p>
                </div>
                <div>
                  <Label className="text-xs text-slate-600">Expiração</Label>
                  <p className="font-medium text-slate-900 flex items-center gap-1">
                    <Calendar className="w-4 h-4" />
                    {format(aiResult.expirationDate!, 'dd/MM/yyyy', { locale: pt })}
                  </p>
                </div>
                <div>
                  <Label className="text-xs text-slate-600">Classificação de Risco</Label>
                  <Badge 
                    variant="outline" 
                    className={
                      aiResult.riskClassification === 'high' 
                        ? 'bg-red-100 text-red-700 border-red-300'
                        : aiResult.riskClassification === 'medium'
                        ? 'bg-yellow-100 text-yellow-700 border-yellow-300'
                        : 'bg-emerald-100 text-emerald-700 border-emerald-300'
                    }
                  >
                    {aiResult.riskClassification === 'high' ? 'Alto' :
                     aiResult.riskClassification === 'medium' ? 'Médio' : 'Baixo'}
                  </Badge>
                </div>
                <div>
                  <Label className="text-xs text-slate-600">Status</Label>
                  <Badge 
                    variant="outline" 
                    className={
                      aiResult.status === 'expired' 
                        ? 'bg-red-100 text-red-700 border-red-300'
                        : aiResult.status === 'expiring_soon'
                        ? 'bg-orange-100 text-orange-700 border-orange-300'
                        : 'bg-emerald-100 text-emerald-700 border-emerald-300'
                    }
                  >
                    {aiResult.status === 'expired' ? 'Expirado' :
                     aiResult.status === 'expiring_soon' ? 'Expirando' : 'Ativo'}
                  </Badge>
                </div>
              </div>

              {aiResult.riskClassification === 'high' && (
                <div className="flex items-start gap-2 p-3 bg-red-50 border border-red-200 rounded-md">
                  <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                  <div className="text-sm">
                    <p className="font-semibold text-red-900">
                      Risco Crítico Detectado
                    </p>
                    <p className="text-red-700">
                      Um registro de risco será criado automaticamente para este contrato.
                    </p>
                  </div>
                </div>
              )}
            </Card>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={handleClose}>
            Cancelar
          </Button>
          {aiResult && (
            <Button onClick={handleSave} className="bg-emerald-600 hover:bg-emerald-700">
              <CheckCircle className="w-4 h-4 mr-2" />
              Salvar Contrato
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

