'use client';

import { useMemo, useState } from 'react';
import type { Contract, Project, Risk } from '@/lib/types';
import { HudBadge, HudButton, HudDrawer, HudInput, HudPanel, HudProgressBar, HudStatusPill } from '@/components/hud';
import { Input } from '@/components/ui/input';
import {
  AlertTriangle,
  BrainCircuit,
  Building2,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  FileSearch,
  FileText,
  Scale,
  ShieldCheck,
  Upload,
  Workflow,
} from 'lucide-react';
import { addDays, differenceInDays } from 'date-fns';

interface ContractUploadProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onContractCreated: (
    contract: Contract,
    autoGeneratedRisk?: Risk,
    metadata?: { file?: File | null; projectId?: string | null; contractType?: string; status?: string; aiPlaceholderRequested?: boolean },
  ) => void | Promise<void>;
  projects?: Project[];
  companies?: string[];
}

const steps = [
  'Informações',
  'Vínculos',
  'Documento',
  'Análise IA',
  'Revisão',
];

const contractTypes = [
  'Prestação de serviços',
  'Fornecimento',
  'Ordem de serviço',
  'Manutenção',
  'Aditivo contratual',
];

const lifecycleStatuses = [
  { value: 'negotiation', label: 'Em negociação' },
  { value: 'legal_review', label: 'Revisão jurídica' },
  { value: 'commercial_review', label: 'Revisão comercial' },
  { value: 'signed', label: 'Assinado' },
  { value: 'active', label: 'Ativo / em execução' },
  { value: 'closed', label: 'Encerrado' },
  { value: 'cancelled', label: 'Cancelado' },
];

function parseNumber(value: string) {
  const normalized = value.replace(/\./g, '').replace(',', '.').replace(/[^\d.]/g, '');
  const parsed = Number(normalized);
  return Number.isFinite(parsed) ? parsed : 0;
}

function toDate(value: string) {
  return value ? new Date(`${value}T00:00:00`) : undefined;
}

export function ContractUpload({
  open,
  onOpenChange,
  onContractCreated,
  projects = [],
  companies = [],
}: ContractUploadProps) {
  const [step, setStep] = useState(0);
  const [file, setFile] = useState<File | null>(null);
  const [analysisStarted, setAnalysisStarted] = useState(false);
  const [form, setForm] = useState({
    name: '',
    company: companies[0] || '',
    projectId: '',
    type: contractTypes[0],
    status: 'negotiation',
    owner: 'Gestão de Contratos',
    value: '',
    signingDate: '',
    expirationDate: '',
  });

  const selectedProject = projects.find((project) => project.id === form.projectId) || null;
  const totalValue = parseNumber(form.value);
  const expirationDate = toDate(form.expirationDate);
  const daysUntilExpiration = expirationDate ? differenceInDays(expirationDate, new Date()) : null;
  const riskClassification: Contract['riskClassification'] =
    totalValue > 5_000_000 || (daysUntilExpiration !== null && daysUntilExpiration <= 45) ? 'high'
      : totalValue > 800_000 || (daysUntilExpiration !== null && daysUntilExpiration <= 120) ? 'medium'
        : 'low';

  const missingInputs = useMemo(() => {
    const missing: string[] = [];
    if (!form.name.trim()) missing.push('Nome do contrato');
    if (!form.company.trim()) missing.push('Empresa vinculada');
    if (!form.owner.trim()) missing.push('Responsável');
    if (!totalValue) missing.push('Valor contratual');
    if ((form.status === 'signed' || form.status === 'active') && !file) {
      missing.push('Documento assinado');
    }
    return missing;
  }, [file, form.company, form.name, form.owner, form.status, totalValue]);

  const setField = (key: keyof typeof form, value: string) => {
    setForm((current) => ({ ...current, [key]: value }));
  };

  const handleClose = () => {
    setStep(0);
    setFile(null);
    setAnalysisStarted(false);
    setForm({
      name: '',
      company: companies[0] || '',
      projectId: '',
      type: contractTypes[0],
      status: 'negotiation',
      owner: 'Gestão de Contratos',
      value: '',
      signingDate: '',
      expirationDate: '',
    });
    onOpenChange(false);
  };

  const handleSave = () => {
    if (missingInputs.length > 0) return;

    const newContract: Contract = {
      id: `contract-${Date.now()}`,
      name: form.name.trim(),
      vendorOrParty: form.company.trim(),
      value: totalValue,
      currency: 'BRL',
      signingDate: toDate(form.signingDate),
      expirationDate: expirationDate || addDays(new Date(), 365),
      renewalDate: expirationDate ? addDays(expirationDate, -60) : undefined,
      fileUrl: file ? URL.createObjectURL(file) : '',
      fileName: file?.name,
      riskClassification,
      status: form.status as Contract['status'],
      uploadedAt: new Date(),
      responsibleName: form.owner.trim(),
      notes: `Tipo: ${form.type} · Ciclo: ${lifecycleStatuses.find((item) => item.value === form.status)?.label || form.status}${selectedProject ? ` · Projeto vinculado: ${selectedProject.codigo}` : ''}. Análise IA mock/pendente, sem chamada a API.`,
      autoExtracted: analysisStarted,
    };

    const autoGeneratedRisk: Risk | undefined = riskClassification === 'high'
      ? {
          id: `risk-${Date.now()}`,
          title: `Triagem contratual de alto risco - ${form.name.trim()}`,
          description: 'Risco criado por regra local de triagem. A análise documental de IA ainda é mock/pendente.',
          category: 'Contractual',
          probability: 4,
          impact: 4,
          level: 16,
          severity: 'critical',
          origin: 'contract',
          referenceId: newContract.id,
          referenceName: newContract.name,
          responsibleName: form.owner.trim(),
          status: 'open',
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      : undefined;

    void Promise.resolve(onContractCreated(newContract, autoGeneratedRisk, {
      file,
      projectId: form.projectId || null,
      contractType: form.type,
      status: form.status,
      aiPlaceholderRequested: analysisStarted,
    })).then(handleClose);
  };

  return (
    <HudDrawer
      isOpen={open}
      onClose={handleClose}
      title="Novo contrato"
      subtitle="Fluxo guiado de governança com análise IA mock/pendente"
      width="720px"
    >
      <div className="space-y-5">
        <HudPanel elevation={1} noPadding interactive={false}>
          <div className="grid grid-cols-5 divide-x divide-ig-border-subtle">
            {steps.map((label, index) => (
              <button
                key={label}
                type="button"
                onClick={() => setStep(index)}
                className={`min-w-0 px-3 py-3 text-left transition-colors ${step === index ? 'bg-ig-accent-weak/50' : 'hover:bg-ig-panel-hover/50'}`}
              >
                <span className="block text-[10px] font-semibold uppercase tracking-[0.14em] text-ig-fg-subtle">
                  Etapa {index + 1}
                </span>
                <span className={`mt-1 block truncate text-xs font-semibold ${step === index ? 'text-ig-accent' : 'text-ig-fg-strong'}`}>
                  {label}
                </span>
              </button>
            ))}
          </div>
        </HudPanel>

        {step === 0 && (
          <HudPanel title="Informações básicas" icon={<FileText className="h-4 w-4" />} interactive={false}>
            <div className="grid gap-4 md:grid-cols-2">
              <label className="md:col-span-2">
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Nome do contrato</span>
                <HudInput value={form.name} onChange={(event) => setField('name', event.target.value)} placeholder="Ex.: OS 0000 - Cliente - escopo" />
              </label>
              <label>
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Tipo de contrato</span>
                <select
                  value={form.type}
                  onChange={(event) => setField('type', event.target.value)}
                  className="h-10 w-full rounded-lg border border-ig-border-strong bg-ig-panel px-3 text-sm text-ig-fg-strong outline-none transition-colors focus:border-ig-border-focus"
                >
                  {contractTypes.map((type) => <option key={type}>{type}</option>)}
                </select>
              </label>
              <label>
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Valor contratual</span>
                <HudInput value={form.value} onChange={(event) => setField('value', event.target.value)} placeholder="R$ 0,00" />
              </label>
              <label className="md:col-span-2">
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Status do ciclo</span>
                <select
                  value={form.status}
                  onChange={(event) => setField('status', event.target.value)}
                  className="h-10 w-full rounded-lg border border-ig-border-strong bg-ig-panel px-3 text-sm text-ig-fg-strong outline-none transition-colors focus:border-ig-border-focus"
                >
                  {lifecycleStatuses.map((statusItem) => (
                    <option key={statusItem.value} value={statusItem.value}>{statusItem.label}</option>
                  ))}
                </select>
                <p className="mt-1.5 text-ig-caption text-ig-fg-muted">
                  Em negociação não exige documento assinado. Assinado/ativo exige anexo do contrato.
                </p>
              </label>
              <label>
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Assinatura</span>
                <HudInput type="date" value={form.signingDate} onChange={(event) => setField('signingDate', event.target.value)} />
              </label>
              <label>
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Vencimento</span>
                <HudInput type="date" value={form.expirationDate} onChange={(event) => setField('expirationDate', event.target.value)} />
              </label>
            </div>
          </HudPanel>
        )}

        {step === 1 && (
          <HudPanel title="Vínculos de referência" subtitle="Empresas e projetos são apenas referências, não cadastros duplicados." icon={<Workflow className="h-4 w-4" />} interactive={false}>
            <div className="grid gap-4 md:grid-cols-2">
              <label>
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Empresa vinculada</span>
                <HudInput
                  list="contract-company-options"
                  value={form.company}
                  onChange={(event) => setField('company', event.target.value)}
                  placeholder="Digite a empresa, cliente ou fornecedor"
                />
                <datalist id="contract-company-options">
                  {companies.map((company) => (
                    <option key={company} value={company} />
                  ))}
                </datalist>
                <p className="mt-1.5 text-ig-caption text-ig-fg-muted">
                  Use uma empresa existente ou informe uma nova contraparte para este contrato.
                </p>
              </label>
              <label>
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Projeto vinculado</span>
                <select
                  value={form.projectId}
                  onChange={(event) => setField('projectId', event.target.value)}
                  className="h-10 w-full rounded-lg border border-ig-border-strong bg-ig-panel px-3 text-sm text-ig-fg-strong outline-none transition-colors focus:border-ig-border-focus"
                >
                  <option value="">Sem projeto vinculado</option>
                  {projects.slice(0, 80).map((project) => (
                    <option key={project.id} value={project.id}>{project.codigo} · {project.nome}</option>
                  ))}
                </select>
              </label>
              <label className="md:col-span-2">
                <span className="mb-1.5 block text-ig-label text-ig-fg-muted">Responsável pelo contrato</span>
                <HudInput value={form.owner} onChange={(event) => setField('owner', event.target.value)} />
              </label>
            </div>
            <div className="mt-4 grid gap-3 md:grid-cols-2">
              <div className="rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                <div className="flex items-center gap-2 text-ig-body-sm font-semibold text-ig-fg-strong">
                  <Building2 className="h-4 w-4 text-ig-accent" />
                  {form.company || 'Empresa não selecionada'}
                </div>
                <p className="mt-1 text-ig-caption text-ig-fg-muted">Referência vinculada ao módulo de empresas/configuração.</p>
              </div>
              <div className="rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                <div className="flex items-center gap-2 text-ig-body-sm font-semibold text-ig-fg-strong">
                  <Workflow className="h-4 w-4 text-ig-accent" />
                  {selectedProject ? `${selectedProject.codigo} · ${selectedProject.nome}` : 'Projeto não vinculado'}
                </div>
                <p className="mt-1 text-ig-caption text-ig-fg-muted">Abertura do detalhe acontece no módulo Projetos.</p>
              </div>
            </div>
          </HudPanel>
        )}

        {step === 2 && (
          <HudPanel title="Documento contratual" icon={<Upload className="h-4 w-4" />} interactive={false}>
            <div className="rounded-xl border border-dashed border-ig-border-focus bg-ig-accent-weak/20 p-5">
              <Input
                type="file"
                accept=".pdf,.doc,.docx"
                onChange={(event) => setFile(event.target.files?.[0] || null)}
                className="border-ig-border-strong bg-ig-panel text-ig-fg-strong file:text-ig-fg-strong"
              />
                <p className="mt-2 text-ig-caption text-ig-fg-muted">
                  O arquivo sera enviado ao bucket privado contract-files ao salvar o contrato.
                </p>
                {form.status !== 'signed' && form.status !== 'active' && (
                  <p className="mt-1 text-ig-caption text-ig-fg-muted">
                    Para contratos em negociação ou revisão, o anexo é opcional.
                  </p>
                )}
            </div>
            {file && (
              <div className="mt-4 flex items-center justify-between gap-3 rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                <div className="min-w-0">
                  <p className="truncate text-ig-body-sm font-semibold text-ig-fg-strong">{file.name}</p>
                  <p className="text-ig-caption text-ig-fg-muted">{Math.round(file.size / 1024)} KB · versão inicial</p>
                </div>
                <HudBadge variant="info">Documento local</HudBadge>
              </div>
            )}
          </HudPanel>
        )}

        {step === 3 && (
          <HudPanel title="Análise IA" subtitle="UI preparada para integração futura; resultado atual é mock/pendente." icon={<BrainCircuit className="h-4 w-4" />} interactive={false}>
            <div className="grid gap-4 lg:grid-cols-[0.95fr_1.05fr]">
              <div className="space-y-3">
                <HudButton
                  variant="primary"
                  fullWidth
                  leftIcon={<FileSearch className="h-4 w-4" />}
                  onClick={() => setAnalysisStarted(true)}
                >
                  Iniciar análise mock
                </HudButton>
                <div className="rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                  <p className="text-ig-body-sm font-semibold text-ig-fg-strong">Status da conexão</p>
                  <p className="mt-1 text-ig-caption text-ig-fg-muted">
                    Nenhuma API de IA foi chamada. A prévia abaixo só demonstra a estrutura esperada.
                  </p>
                </div>
                <HudProgressBar value={analysisStarted ? 68 : 0} variant="info" />
              </div>
              <div className="space-y-2">
                {[
                  'Resumo executivo',
                  'Cláusulas-chave',
                  'Condições de pagamento',
                  'Renovação e rescisão',
                  'Penalidades e multas',
                  'Obrigações de SLA',
                  'Riscos legais e financeiros',
                  'Informações faltantes',
                  'Documentos requeridos',
                  'Ações de governança sugeridas',
                  'Rota de aprovação recomendada',
                ].map((item) => (
                  <div key={item} className="flex items-center justify-between gap-3 rounded-lg border border-ig-border-subtle bg-ig-panel/45 px-3 py-2">
                    <span className="text-ig-body-sm text-ig-fg-strong">{item}</span>
                    <HudBadge variant={analysisStarted ? 'info' : 'neutral'} size="sm">
                      {analysisStarted ? 'mock pendente' : 'aguardando'}
                    </HudBadge>
                  </div>
                ))}
              </div>
            </div>
          </HudPanel>
        )}

        {step === 4 && (
          <HudPanel title="Revisão e salvamento" icon={<ShieldCheck className="h-4 w-4" />} interactive={false}>
            <div className="grid gap-4 lg:grid-cols-3">
              <div className="rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                <p className="text-ig-label text-ig-fg-muted">Risco de triagem</p>
                <HudStatusPill className="mt-2" variant={riskClassification === 'high' ? 'critical' : riskClassification === 'medium' ? 'warning' : 'active'}>
                  {riskClassification === 'high' ? 'Alto' : riskClassification === 'medium' ? 'Médio' : 'Baixo'}
                </HudStatusPill>
              </div>
              <div className="rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                <p className="text-ig-label text-ig-fg-muted">Aprovação</p>
                <p className="mt-2 text-ig-body-sm font-semibold text-ig-fg-strong">
                  {riskClassification === 'high' ? 'Jurídico + Financeiro + Comitê' : 'Jurídico + gestor'}
                </p>
              </div>
              <div className="rounded-lg border border-ig-border-subtle bg-ig-panel/55 p-3">
                <p className="text-ig-label text-ig-fg-muted">IA</p>
                <p className="mt-2 text-ig-body-sm font-semibold text-ig-fg-strong">
                  {analysisStarted ? 'Mock pendente' : 'Não iniciada'}
                </p>
              </div>
            </div>

            {missingInputs.length > 0 && (
              <div className="mt-4 rounded-lg border border-[color-mix(in_oklab,var(--ig-warning)_34%,transparent)] bg-[color-mix(in_oklab,var(--ig-warning)_10%,transparent)] p-3">
                <div className="flex items-start gap-2">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-ig-warning" />
                  <div>
                    <p className="text-ig-body-sm font-semibold text-ig-fg-strong">Campos pendentes</p>
                    <p className="mt-1 text-ig-caption text-ig-fg-muted">{missingInputs.join(', ')}</p>
                  </div>
                </div>
              </div>
            )}
          </HudPanel>
        )}

        <div className="flex items-center justify-between border-t border-ig-border-subtle pt-4">
          <HudButton
            variant="ghost"
            leftIcon={<ChevronLeft className="h-4 w-4" />}
            disabled={step === 0}
            onClick={() => setStep((current) => Math.max(0, current - 1))}
          >
            Voltar
          </HudButton>
          <div className="flex items-center gap-2">
            <HudButton variant="secondary" onClick={handleClose}>
              Cancelar
            </HudButton>
            {step < steps.length - 1 ? (
              <HudButton
                variant="primary"
                rightIcon={<ChevronRight className="h-4 w-4" />}
                onClick={() => setStep((current) => Math.min(steps.length - 1, current + 1))}
              >
                Avançar
              </HudButton>
            ) : (
              <HudButton
                variant="primary"
                leftIcon={<CheckCircle className="h-4 w-4" />}
                disabled={missingInputs.length > 0}
                onClick={handleSave}
              >
                Salvar contrato
              </HudButton>
            )}
          </div>
        </div>
      </div>
    </HudDrawer>
  );
}
