'use client';

import { useState, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import type { Contract, Risk, Project } from "@/lib/types";
import {
  FileCheck,
  Upload,
  Search,
  DollarSign,
  Clock,
  CheckCircle,
  Building2,
  TrendingUp,
  FileText,
  AlertTriangle,
  Briefcase,
  Plus,
} from "lucide-react";
import { differenceInDays } from "date-fns";

// Components
import { ContractUpload } from "@/components/contracts/contract-upload";
import { ContractList } from "@/components/contracts/contract-list";
import { ContractBriefPanel } from "@/components/contracts/ContractBriefPanel";
import { ContractsByCompanyModule } from "@/components/contracts/ContractsByCompanyModule";
import { ProjectDetailDrawer } from "@/components/portfolio/ProjectDetailDrawer";
import { getProjects } from "@/lib/services/projects";
import { portfolioTotals } from "@/data/portfolioContracts";
import { excelContracts } from "@/data/contractsFromExcel.generated";

// New Glass HUD Components
import {
  HudPageLayout,
  HudHeader,
  HudKpiStrip,
  HudFilterBar,
  HudPanel,
  HudButton,
  HudBadge,
  HudStatusPill,
  HudTabs,
  HudDrawer,
  type KpiItem,
  type FilterGroup,
  type HudTab,
} from "@/components/hud";

export default function ContratosPage() {
  const router = useRouter();
  const t = useTranslations('contracts');
  const tCommon = useTranslations('common');

  const [contracts, setContracts] = useState<Contract[]>(excelContracts);
  const [uploadOpen, setUploadOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [riskFilter, setRiskFilter] = useState('all');
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [projectDrawerOpen, setProjectDrawerOpen] = useState(false);
  const [activeView, setActiveView] = useState<'contracts' | 'companies' | 'projects'>('contracts');
  const [selectedContractId, setSelectedContractId] = useState<string | null>(null);

  // Load projects on mount
  useEffect(() => {
    setProjects(getProjects());
  }, []);

  // Handle project click
  const handleProjectClick = (project: Project) => {
    setSelectedProject(project);
    setProjectDrawerOpen(true);
  };

  // Calculate KPIs
  const stats = useMemo(() => {
    const now = new Date();
    const renewals90d = contracts.filter((c) => {
      if (!c.expirationDate) return false;
      const days = differenceInDays(new Date(c.expirationDate), now);
      return days >= 0 && days <= 90;
    }).length;

    const missingDocs = contracts.filter((c) => !c.fileUrl || c.fileUrl === '').length;

    return {
      total: contracts.length,
      active: contracts.filter((c) => c.status === 'active').length,
      expiring: contracts.filter((c) => c.status === 'expiring_soon').length,
      highRisk: contracts.filter((c) => c.riskClassification === 'high').length,
      totalValue: contracts.reduce((sum, c) => sum + c.value, 0),
      renewals90d,
      missingDocs,
    };
  }, [contracts]);

  // Filter contracts
  const filteredContracts = useMemo(() => {
    return contracts.filter((contract) => {
      const matchesSearch =
        contract.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        contract.vendorOrParty.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesStatus = statusFilter === 'all' || contract.status === statusFilter;
      const matchesRisk = riskFilter === 'all' || contract.riskClassification === riskFilter;

      return matchesSearch && matchesStatus && matchesRisk;
    });
  }, [contracts, searchTerm, statusFilter, riskFilter]);

  const selectedContract = useMemo(() => {
    if (!selectedContractId) return null;
    return contracts.find((c) => c.id === selectedContractId) || null;
  }, [contracts, selectedContractId]);

  const handleContractCreated = (contract: Contract, autoGeneratedRisk?: Risk) => {
    setContracts((prev) => [contract, ...prev]);

    if (autoGeneratedRisk) {
      alert(`✅ Contrato salvo!\n⚠️ Risco crítico detectado e registrado: "${autoGeneratedRisk.title}"`);
    }
  };

  const handleSelectContract = (contract: Contract) => {
    setSelectedContractId(contract.id);
  };

  const handleViewContract = (contract: Contract) => {
    router.push(`/contratos/${contract.id}`);
  };

  const formatCurrency = (value: number) =>
    new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL',
      notation: 'compact',
      minimumFractionDigits: 0,
      maximumFractionDigits: 1,
    }).format(value);

  // KPI items
  const kpiItems: KpiItem[] = useMemo(() => [
    {
      id: 'exposure',
      value: formatCurrency(portfolioTotals.totalContracted),
      label: t('exposure'),
      variant: 'info',
      icon: <DollarSign className="w-5 h-5" />,
    },
    {
      id: 'backlog',
      value: formatCurrency(portfolioTotals.backlogToInvoice),
      label: t('backlog'),
      variant: 'warning',
      icon: <Clock className="w-5 h-5" />,
    },
    {
      id: 'billed',
      value: formatCurrency(portfolioTotals.totalInvoiced),
      label: t('billed'),
      variant: 'success',
      icon: <CheckCircle className="w-5 h-5" />,
    },
    {
      id: 'renewals',
      value: stats.renewals90d,
      label: t('renewals90d'),
      variant: stats.renewals90d > 0 ? 'warning' : 'default',
      icon: <TrendingUp className="w-5 h-5" />,
    },
    {
      id: 'highRisk',
      value: stats.highRisk,
      label: t('highRisk'),
      variant: stats.highRisk > 0 ? 'danger' : 'default',
      icon: <AlertTriangle className="w-5 h-5" />,
    },
    {
      id: 'missingDocs',
      value: stats.missingDocs,
      label: t('missingDocs'),
      variant: stats.missingDocs > 0 ? 'warning' : 'default',
      icon: <FileText className="w-5 h-5" />,
    },
  ], [stats, t]);

  // Filter groups
  const filterGroups: FilterGroup[] = useMemo(() => [
    {
      id: 'status',
      label: tCommon('status'),
      value: statusFilter,
      options: [
        { value: 'all', label: t('allStatus') },
        { value: 'active', label: t('active') },
        { value: 'expiring_soon', label: t('expiringSoon') },
        { value: 'expired', label: t('expired') },
      ],
      onChange: setStatusFilter,
    },
    {
      id: 'risk',
      label: t('riskClassification'),
      value: riskFilter,
      options: [
        { value: 'all', label: t('allRisks') },
        { value: 'low', label: t('riskLow') },
        { value: 'medium', label: t('riskMedium') },
        { value: 'high', label: t('riskHigh') },
      ],
      onChange: setRiskFilter,
    },
  ], [statusFilter, riskFilter, t, tCommon]);

  const activeFiltersCount = useMemo(() => {
    let count = 0;
    if (statusFilter !== 'all') count++;
    if (riskFilter !== 'all') count++;
    return count;
  }, [statusFilter, riskFilter]);

  const handleClearFilters = () => {
    setStatusFilter('all');
    setRiskFilter('all');
    setSearchTerm('');
  };

  // Tabs configuration
  const tabs: HudTab[] = useMemo(() => [
    {
      id: 'contracts',
      label: tCommon('contracts'),
      icon: <FileText className="w-4 h-4" />,
      badge: contracts.length,
      content: (
        <div className="space-y-4">
          <HudPanel title={tCommon('filters')} icon={<Search className="w-4 h-4" />} accentColor="cyan">
            <HudFilterBar
              searchPlaceholder={t('searchPlaceholder')}
              searchValue={searchTerm}
              onSearchChange={setSearchTerm}
              filterGroups={filterGroups}
              activeFiltersCount={activeFiltersCount}
              onClearFilters={handleClearFilters}
              compact
            />
          </HudPanel>

          <HudPanel noPadding>
            <ContractList
              contracts={filteredContracts}
              selectedContractId={selectedContractId}
              onSelectContract={handleSelectContract}
              onViewContract={handleViewContract}
              onDownloadContract={() => {}}
            />
          </HudPanel>
        </div>
      ),
    },
    {
      id: 'companies',
      label: t('companies'),
      icon: <Building2 className="w-4 h-4" />,
      badge: portfolioTotals.totalContracts,
      content: (
        <ContractsByCompanyModule
          projects={projects}
          onProjectClick={handleProjectClick}
        />
      ),
    },
    {
      id: 'projects',
      label: tCommon('projects'),
      icon: <Briefcase className="w-4 h-4" />,
      badge: projects.length,
      content: (
        <HudPanel title={t('projectsLinkedToContracts')}>
          <div className="space-y-3 max-h-[600px] overflow-y-auto">
            {projects.slice(0, 20).map((project) => (
              <div
                key={project.id}
                onClick={() => handleProjectClick(project)}
                className="p-4 rounded-lg bg-white/[0.02] border border-white/[0.06] hover:border-cyan-500/30 transition-colors cursor-pointer"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <HudBadge variant="outline" size="sm">{project.codigo}</HudBadge>
                      <HudStatusPill
                        variant={
                          project.status === 'em_andamento'
                            ? 'active'
                            : project.status === 'concluido'
                            ? 'completed'
                            : project.status === 'cancelado'
                            ? 'error'
                            : 'neutral'
                        }
                        size="sm"
                      >
                        {project.status?.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())}
                      </HudStatusPill>
                    </div>
                    <p className="text-sm font-medium text-white truncate">{project.nome}</p>
                    <p className="text-xs text-white/50 mt-1">{project.cliente}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-sm font-semibold text-white">
                      {formatCurrency(project.valor_total)}
                    </p>
                    <p className="text-xs text-white/50">{project.progresso_percentual || 0}% completo</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </HudPanel>
      ),
    },
  ], [contracts.length, filteredContracts, filterGroups, handleProjectClick, handleSelectContract, handleViewContract, portfolioTotals.totalContracts, projects, riskFilter, searchTerm, selectedContractId, statusFilter, t, tCommon, activeFiltersCount]);

  return (
    <HudPageLayout>
      {/* Header */}
      <HudHeader
        title={t('title')}
        subtitle={t('subtitle')}
        icon={<FileCheck className="w-5 h-5" />}
        breadcrumbs={[{ label: t('title') }]}
        actions={
          <HudButton
            variant="primary"
            size="md"
            leftIcon={<Plus className="w-4 h-4" />}
            onClick={() => setUploadOpen(true)}
          >
            {t('newContract')}
          </HudButton>
        }
      />

      {/* KPI Strip */}
      <HudKpiStrip kpis={kpiItems} columns={6} className="mb-6" />

      {/* Tabs Content */}
      <HudTabs
        tabs={tabs}
        activeTab={activeView}
        onTabChange={(v) => setActiveView(v as typeof activeView)}
        variant="default"
      />

      {/* Side Panel for Contract Details (when in contracts view) */}
      {activeView === 'contracts' && selectedContract && (
        <HudDrawer
          isOpen={!!selectedContract}
          onClose={() => setSelectedContractId(null)}
          title={selectedContract.name}
          subtitle={selectedContract.vendorOrParty}
          position="right"
          width="400px"
        >
          <ContractBriefPanel
            contract={selectedContract}
            onViewContract={handleViewContract}
            onDownloadContract={() => {}}
          />
        </HudDrawer>
      )}

      {/* Project Detail Drawer */}
      <ProjectDetailDrawer
        project={selectedProject}
        open={projectDrawerOpen}
        onOpenChange={setProjectDrawerOpen}
      />

      {/* Upload Dialog */}
      <ContractUpload
        open={uploadOpen}
        onOpenChange={setUploadOpen}
        onContractCreated={handleContractCreated}
      />
    </HudPageLayout>
  );
}
