import type { ExtendedRisk } from "./risk-types";

function d(str: string) { return new Date(str); }

export const MOCK_RISKS: ExtendedRisk[] = [
  {
    id: "RSK-001",
    title: "Risco de Atraso em Projeto Crítico",
    description: "Projeto de infraestrutura com potencial de atraso devido a falta de recursos e conflitos de cronograma com fornecedores-chave.",
    category: "Operational",
    area: "Operações",
    probability: 4,
    impact: 5,
    level: 20,
    severity: "critical",
    origin: "project",
    referenceId: "proj-123",
    responsibleName: "PMO Corporativo",
    status: "open",
    mitigationPlan: "Realocar equipe de backup e renegociar prazos com fornecedor principal.",
    nextAction: "Reunião de alinhamento com fornecedor — 12/02",
    dueDate: d("2024-03-15"),
    createdAt: d("2024-01-10"),
    updatedAt: d("2024-02-08"),
    actions: [
      { id: "a1", riskId: "RSK-001", title: "Agendar reunião com fornecedor", assignee: "PMO Corporativo", dueDate: d("2024-02-12"), status: "pending", createdAt: d("2024-02-01") },
      { id: "a2", riskId: "RSK-001", title: "Atualizar cronograma mestre", assignee: "PMO Corporativo", dueDate: d("2024-02-20"), status: "pending", createdAt: d("2024-02-01") },
    ],
    history: [
      { id: "h1", riskId: "RSK-001", action: "Risco identificado", user: "Sistema", timestamp: d("2024-01-10") },
      { id: "h2", riskId: "RSK-001", action: "Severidade reclassificada para Crítico", user: "Ana Costa", timestamp: d("2024-01-18"), detail: "Probabilidade atualizada de 3 para 4." },
      { id: "h3", riskId: "RSK-001", action: "Plano de mitigação definido", user: "Carlos Lima", timestamp: d("2024-02-01") },
    ],
    evidences: [
      { id: "e1", riskId: "RSK-001", name: "Relatório de cronograma v3.pdf", type: "document", uploadedAt: d("2024-01-15"), uploadedBy: "PMO Corporativo" },
    ],
  },
  {
    id: "RSK-002",
    title: "Exposição Cambial em Contrato Internacional",
    description: "Variação cambial pode impactar negativamente o valor do contrato com fornecedor europeu.",
    category: "Financial",
    area: "Financeiro",
    probability: 3,
    impact: 4,
    level: 12,
    severity: "high",
    origin: "contract",
    referenceId: "contract-456",
    responsibleName: "Tesouraria",
    status: "mitigating",
    mitigationPlan: "Hedge cambial parcial (70%) e renegociação de cláusulas de reajuste.",
    nextAction: "Fechar operação de hedge — 15/02",
    dueDate: d("2024-02-28"),
    createdAt: d("2024-01-15"),
    updatedAt: d("2024-01-25"),
    actions: [
      { id: "a3", riskId: "RSK-002", title: "Fechar hedge cambial 70%", assignee: "Tesouraria", dueDate: d("2024-02-15"), status: "in_progress", createdAt: d("2024-01-20") },
    ],
    history: [
      { id: "h4", riskId: "RSK-002", action: "Risco identificado via análise contratual", user: "Sistema", timestamp: d("2024-01-15") },
      { id: "h5", riskId: "RSK-002", action: "Status alterado para Mitigando", user: "Fernanda Reis", timestamp: d("2024-01-25") },
    ],
    evidences: [
      { id: "e2", riskId: "RSK-002", name: "Cotação hedge jan-2024.xlsx", type: "document", uploadedAt: d("2024-01-22"), uploadedBy: "Tesouraria" },
    ],
  },
  {
    id: "RSK-003",
    title: "Não Conformidade com LGPD",
    description: "Processos de tratamento de dados pessoais não atendem todos os requisitos da LGPD. Risco de sanção pela ANPD.",
    category: "Legal",
    area: "Jurídico",
    probability: 2,
    impact: 5,
    level: 10,
    severity: "medium",
    origin: "manual",
    responsibleName: "Jurídico",
    status: "open",
    mitigationPlan: "Adequação completa dos processos de tratamento e nomeação de DPO.",
    nextAction: "Contratar DPO externo — 01/03",
    dueDate: d("2024-04-01"),
    createdAt: d("2024-01-20"),
    updatedAt: d("2024-01-20"),
    actions: [
      { id: "a4", riskId: "RSK-003", title: "Mapear fluxos de dados pessoais", assignee: "Jurídico", dueDate: d("2024-02-28"), status: "pending", createdAt: d("2024-01-20") },
    ],
    history: [
      { id: "h6", riskId: "RSK-003", action: "Risco identificado", user: "Auditoria Interna", timestamp: d("2024-01-20") },
    ],
    evidences: [],
  },
  {
    id: "RSK-004",
    title: "Cláusula Contratual Desfavorável",
    description: "Contrato com fornecedor crítico contém penalidades elevadas (20% do valor) em caso de rescisão antecipada.",
    category: "Contractual",
    area: "Operações",
    probability: 4,
    impact: 4,
    level: 16,
    severity: "critical",
    origin: "contract",
    referenceId: "contract-789",
    responsibleName: "Suprimentos",
    status: "open",
    nextAction: "Solicitar renegociação de cláusula penal",
    dueDate: d("2024-03-01"),
    createdAt: d("2024-01-22"),
    updatedAt: d("2024-01-22"),
    actions: [],
    history: [
      { id: "h7", riskId: "RSK-004", action: "Risco identificado via análise contratual", user: "IA Contratual", timestamp: d("2024-01-22") },
    ],
    evidences: [
      { id: "e3", riskId: "RSK-004", name: "Contrato FORN-789 - Cláusula 14.pdf", type: "document", uploadedAt: d("2024-01-22"), uploadedBy: "Suprimentos" },
    ],
  },
  {
    id: "RSK-005",
    title: "Falta de Auditoria Interna",
    description: "Ausência de controles de auditoria interna pode gerar problemas de compliance e exposição regulatória.",
    category: "Compliance",
    area: "Compliance",
    probability: 3,
    impact: 3,
    level: 9,
    severity: "medium",
    origin: "manual",
    responsibleName: "Auditoria",
    status: "resolved",
    mitigationPlan: "Implementar programa de auditoria interna trimestral.",
    createdAt: d("2024-01-05"),
    updatedAt: d("2024-01-28"),
    resolvedAt: d("2024-01-28"),
    actions: [
      { id: "a5", riskId: "RSK-005", title: "Publicar programa de auditoria 2024", assignee: "Auditoria", dueDate: d("2024-01-25"), status: "done", createdAt: d("2024-01-06") },
    ],
    history: [
      { id: "h8", riskId: "RSK-005", action: "Risco identificado", user: "Comitê Executivo", timestamp: d("2024-01-05") },
      { id: "h9", riskId: "RSK-005", action: "Resolvido — programa implementado", user: "Auditoria", timestamp: d("2024-01-28") },
    ],
    evidences: [],
  },
  {
    id: "RSK-006",
    title: "Ruptura na Cadeia de Fornecimento",
    description: "Fornecedor-chave de componentes eletrônicos apresenta instabilidade financeira. Risco de interrupção na produção.",
    category: "Operational",
    area: "Supply Chain",
    probability: 3,
    impact: 5,
    level: 15,
    severity: "high",
    origin: "manual",
    responsibleName: "Supply Chain",
    status: "mitigating",
    mitigationPlan: "Homologar fornecedor alternativo e aumentar estoque de segurança para 60 dias.",
    nextAction: "Avaliar proposta de fornecedor alternativo — 18/02",
    dueDate: d("2024-03-10"),
    createdAt: d("2024-02-01"),
    updatedAt: d("2024-02-10"),
    actions: [
      { id: "a6", riskId: "RSK-006", title: "Auditar saúde financeira do fornecedor atual", assignee: "Supply Chain", dueDate: d("2024-02-15"), status: "done", createdAt: d("2024-02-02") },
      { id: "a7", riskId: "RSK-006", title: "Avaliar fornecedor alternativo", assignee: "Supply Chain", dueDate: d("2024-02-18"), status: "in_progress", createdAt: d("2024-02-05") },
    ],
    history: [
      { id: "h10", riskId: "RSK-006", action: "Risco identificado", user: "Supply Chain", timestamp: d("2024-02-01") },
      { id: "h11", riskId: "RSK-006", action: "Mitigação iniciada", user: "Supply Chain", timestamp: d("2024-02-05") },
    ],
    evidences: [
      { id: "e4", riskId: "RSK-006", name: "Análise financeira fornecedor A.pdf", type: "document", uploadedAt: d("2024-02-10"), uploadedBy: "Supply Chain" },
    ],
  },
  {
    id: "RSK-007",
    title: "Multa Regulatória Ambiental",
    description: "Não-conformidade ambiental em unidade operacional do interior pode gerar sanção do IBAMA.",
    category: "Compliance",
    area: "Compliance",
    probability: 2,
    impact: 4,
    level: 8,
    severity: "medium",
    origin: "project",
    referenceId: "proj-789",
    responsibleName: "Meio Ambiente",
    status: "open",
    mitigationPlan: "Adequar licenças ambientais e implementar programa de monitoramento.",
    nextAction: "Submeter pedido de renovação de licença — 20/02",
    dueDate: d("2024-03-30"),
    createdAt: d("2024-02-05"),
    updatedAt: d("2024-02-12"),
    actions: [
      { id: "a8", riskId: "RSK-007", title: "Renovar licença ambiental LP-204", assignee: "Meio Ambiente", dueDate: d("2024-02-20"), status: "pending", createdAt: d("2024-02-05") },
    ],
    history: [
      { id: "h12", riskId: "RSK-007", action: "Risco identificado via inspeção", user: "Meio Ambiente", timestamp: d("2024-02-05") },
    ],
    evidences: [],
  },
  {
    id: "RSK-008",
    title: "Vulnerabilidade de Segurança em Sistema",
    description: "Sistema legado ERP com vulnerabilidades CVE-2024 críticas. Necessita atualização urgente para evitar data breach.",
    category: "Operational",
    area: "TI",
    probability: 5,
    impact: 4,
    level: 20,
    severity: "critical",
    origin: "manual",
    responsibleName: "TI / Segurança",
    status: "mitigating",
    mitigationPlan: "Aplicar patches de segurança e migrar módulos críticos para versão cloud.",
    nextAction: "Deploy de patch de segurança — 16/02",
    dueDate: d("2024-02-20"),
    createdAt: d("2024-02-08"),
    updatedAt: d("2024-02-15"),
    actions: [
      { id: "a9", riskId: "RSK-008", title: "Aplicar patch CVE-2024-1234", assignee: "TI / Segurança", dueDate: d("2024-02-16"), status: "in_progress", createdAt: d("2024-02-09") },
      { id: "a10", riskId: "RSK-008", title: "Planejamento de migração cloud", assignee: "TI / Segurança", dueDate: d("2024-03-15"), status: "pending", createdAt: d("2024-02-10") },
    ],
    history: [
      { id: "h13", riskId: "RSK-008", action: "Vulnerabilidade detectada via scan", user: "SIEM", timestamp: d("2024-02-08") },
      { id: "h14", riskId: "RSK-008", action: "Classificado como Crítico — P5 × I4", user: "CISO", timestamp: d("2024-02-09") },
      { id: "h15", riskId: "RSK-008", action: "Mitigação iniciada — patching", user: "TI / Segurança", timestamp: d("2024-02-10") },
    ],
    evidences: [
      { id: "e5", riskId: "RSK-008", name: "Scan report CVE-2024.pdf", type: "document", uploadedAt: d("2024-02-08"), uploadedBy: "SIEM" },
    ],
  },
  {
    id: "RSK-009",
    title: "Flutuação de Juros no Financiamento",
    description: "Variação SELIC pode impactar custo de capital dos projetos financiados com taxa pós-fixada.",
    category: "Financial",
    area: "Financeiro",
    probability: 3,
    impact: 3,
    level: 9,
    severity: "medium",
    origin: "manual",
    responsibleName: "Tesouraria",
    status: "open",
    nextAction: "Simular cenários de taxa para Q2",
    dueDate: d("2024-03-15"),
    createdAt: d("2024-02-10"),
    updatedAt: d("2024-02-10"),
    actions: [],
    history: [
      { id: "h16", riskId: "RSK-009", action: "Risco identificado", user: "Tesouraria", timestamp: d("2024-02-10") },
    ],
    evidences: [],
  },
  {
    id: "RSK-010",
    title: "Perda de Funcionário-Chave",
    description: "Especialista sênior de engenharia com conhecimento único do projeto pode deixar a empresa. Conhecimento não documentado.",
    category: "Operational",
    area: "Operações",
    probability: 2,
    impact: 3,
    level: 6,
    severity: "low",
    origin: "manual",
    responsibleName: "RH Corporativo",
    status: "resolved",
    mitigationPlan: "Knowledge base documentada e plano de sucessão implementado.",
    createdAt: d("2024-01-08"),
    updatedAt: d("2024-02-20"),
    resolvedAt: d("2024-02-20"),
    actions: [
      { id: "a11", riskId: "RSK-010", title: "Documentar knowledge base", assignee: "RH Corporativo", dueDate: d("2024-02-10"), status: "done", createdAt: d("2024-01-10") },
    ],
    history: [
      { id: "h17", riskId: "RSK-010", action: "Risco identificado", user: "RH", timestamp: d("2024-01-08") },
      { id: "h18", riskId: "RSK-010", action: "Resolvido — documentação concluída", user: "RH Corporativo", timestamp: d("2024-02-20") },
    ],
    evidences: [],
  },
];

/* ── Trend data for line chart ── */
export const TREND_DATA = [
  { month: "Set", critical: 1, high: 2, medium: 3 },
  { month: "Out", critical: 2, high: 2, medium: 4 },
  { month: "Nov", critical: 2, high: 3, medium: 3 },
  { month: "Dez", critical: 3, high: 2, medium: 4 },
  { month: "Jan", critical: 3, high: 3, medium: 4 },
  { month: "Fev", critical: 3, high: 2, medium: 4 },
];
