import type {
  Deliberacao,
  DeliberacaoStatus,
  SlaStatus,
} from './types';

const COMITES = [
  { id: 'cmt-exec', nome: 'Comitê Executivo', cor: '#FF7A3D' },
  { id: 'cmt-fin', nome: 'Comitê Financeiro', cor: '#008751' },
  { id: 'cmt-aud', nome: 'Comitê de Auditoria', cor: '#3F51B5' },
  { id: 'cmt-est', nome: 'Comitê Estratégico', cor: '#9C27B0' },
  { id: 'cmt-risk', nome: 'Comitê de Riscos', cor: '#FFB347' },
  { id: 'cmt-gov', nome: 'Comitê de Governança', cor: '#4CAF7B' },
];

const RESPONSAVEIS = [
  { nome: 'Marina Costa', email: 'marina.costa@insight.com' },
  { nome: 'Rafael Andrade', email: 'rafael.andrade@insight.com' },
  { nome: 'Beatriz Mendes', email: 'beatriz.mendes@insight.com' },
  { nome: 'Lucas Oliveira', email: 'lucas.oliveira@insight.com' },
  { nome: 'Ana Paula Reis', email: 'ana.reis@insight.com' },
  { nome: 'Felipe Tavares', email: 'felipe.tavares@insight.com' },
];

export const DELIBERACOES_MOCK: Deliberacao[] = [
  {
    id: 'dlb-001',
    titulo: 'Aprovação do CAPEX 2026 — Expansão Subestação Sul',
    descricao:
      'Investimento de R$ 48M para ampliação da capacidade da subestação Sul, atendendo demanda projetada de 2026–2028. Análise técnica e financeira completas anexadas.',
    contexto:
      'Crescimento orgânico de 18% a.a. na carteira regional Sul exige ampliação imediata. Atraso compromete contratos firmados de fornecimento.',
    decisao_solicitada:
      'Aprovar investimento de R$ 48M com cronograma de desembolso em 3 tranches (Q1, Q2, Q3 de 2026).',
    comite_id: COMITES[0].id,
    comite_nome: COMITES[0].nome,
    comite_cor: COMITES[0].cor,
    responsavel_nome: RESPONSAVEIS[0].nome,
    responsavel_email: RESPONSAVEIS[0].email,
    status: 'em_votacao',
    prioridade: 'critica',
    risco: 'alto',
    sla_status: 'at_risk',
    sla_deadline: '2026-05-08T18:00:00Z',
    quorum_necessario: 7,
    quorum_atual: 5,
    votos_favor: 3,
    votos_contra: 1,
    votos_abstencao: 1,
    proxima_acao: 'Aguardando voto de 2 conselheiros até 08/05',
    pareceres: [
      {
        id: 'p-001',
        autor_nome: 'Dr. Carlos Eduardo (Jurídico)',
        tipo: 'juridico',
        conteudo: 'Sem óbices contratuais. Cláusulas de garantia revisadas e em conformidade.',
        status: 'favoravel',
        created_at: '2026-04-28T10:00:00Z',
      },
      {
        id: 'p-002',
        autor_nome: 'CFO Ricardo Lima',
        tipo: 'financeiro',
        conteudo: 'Payback de 4.2 anos, TIR 17.8%. Estrutura de capital mantida. Aprovado com ressalvas sobre cronograma.',
        status: 'com_ressalvas',
        created_at: '2026-04-29T14:30:00Z',
      },
      {
        id: 'p-003',
        autor_nome: 'Eng. Patrícia Souza',
        tipo: 'tecnico',
        conteudo: 'Especificações técnicas validadas. Capacidade dimensionada conforme estudo de carga.',
        status: 'favoravel',
        created_at: '2026-04-30T09:15:00Z',
      },
    ],
    evidencias: [
      {
        id: 'e-001',
        nome: 'Estudo Técnico Subestação Sul.pdf',
        url: '#',
        tipo: 'documento',
        uploaded_by: 'Marina Costa',
        created_at: '2026-04-25T11:00:00Z',
      },
      {
        id: 'e-002',
        nome: 'Análise Financeira CAPEX 2026.xlsx',
        url: '#',
        tipo: 'relatorio',
        uploaded_by: 'CFO Ricardo Lima',
        created_at: '2026-04-29T14:00:00Z',
      },
    ],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-001',
        acao: 'Deliberação criada',
        descricao: 'Pauta submetida ao Comitê Executivo',
        usuario_nome: 'Marina Costa',
        timestamp: '2026-04-25T09:00:00Z',
      },
      {
        id: 'a-002',
        acao: 'Parecer adicionado',
        descricao: 'Parecer jurídico favorável',
        usuario_nome: 'Dr. Carlos Eduardo',
        timestamp: '2026-04-28T10:00:00Z',
      },
      {
        id: 'a-003',
        acao: 'Votação iniciada',
        descricao: 'Período de votação aberto até 08/05',
        usuario_nome: 'Sistema',
        timestamp: '2026-05-01T08:00:00Z',
      },
    ],
    itens_relacionados: [
      { id: 'pj-101', label: 'Projeto Subestação Sul', tipo: 'projeto', href: '/projetos/pj-101' },
      { id: 'r-051', label: 'Risco operacional regional', tipo: 'risco', href: '/riscos/r-051' },
    ],
    created_at: '2026-04-25T09:00:00Z',
    updated_at: '2026-05-01T08:00:00Z',
  },
  {
    id: 'dlb-002',
    titulo: 'Renovação Contrato Fornecedor Crítico — Schneider',
    descricao:
      'Renovação do contrato de manutenção com Schneider Electric por 36 meses. Reajuste de 6.2% sobre valor anterior.',
    contexto: 'Contrato vigente expira em 30/06/2026. Schneider é fornecedor exclusivo de equipamentos críticos.',
    decisao_solicitada: 'Aprovar renovação contratual de R$ 12.4M por 36 meses.',
    comite_id: COMITES[1].id,
    comite_nome: COMITES[1].nome,
    comite_cor: COMITES[1].cor,
    responsavel_nome: RESPONSAVEIS[1].nome,
    responsavel_email: RESPONSAVEIS[1].email,
    status: 'em_revisao',
    prioridade: 'alta',
    risco: 'medio',
    sla_status: 'on_track',
    sla_deadline: '2026-05-20T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 0,
    votos_favor: 0,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Aguardando parecer financeiro até 12/05',
    pareceres: [
      {
        id: 'p-004',
        autor_nome: 'Dr. Carlos Eduardo (Jurídico)',
        tipo: 'juridico',
        conteudo: 'Cláusula de reajuste em conformidade com IPCA. Penalidades equilibradas.',
        status: 'favoravel',
        created_at: '2026-05-02T11:00:00Z',
      },
    ],
    evidencias: [
      {
        id: 'e-003',
        nome: 'Contrato Schneider — Minuta v3.pdf',
        url: '#',
        tipo: 'documento',
        uploaded_by: 'Rafael Andrade',
        created_at: '2026-04-30T14:00:00Z',
      },
    ],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-004',
        acao: 'Deliberação criada',
        descricao: 'Renovação contratual submetida',
        usuario_nome: 'Rafael Andrade',
        timestamp: '2026-04-30T14:00:00Z',
      },
      {
        id: 'a-005',
        acao: 'Parecer jurídico recebido',
        descricao: 'Parecer favorável adicionado',
        usuario_nome: 'Dr. Carlos Eduardo',
        timestamp: '2026-05-02T11:00:00Z',
      },
    ],
    itens_relacionados: [
      { id: 'ct-201', label: 'Contrato Schneider FW-2023', tipo: 'contrato', href: '/contratos/ct-201' },
    ],
    created_at: '2026-04-30T14:00:00Z',
    updated_at: '2026-05-02T11:00:00Z',
  },
  {
    id: 'dlb-003',
    titulo: 'Aprovação Política de Compliance Anticorrupção',
    descricao:
      'Atualização da política interna de compliance alinhada à Lei 12.846/2013 e diretrizes ISO 37001.',
    contexto: 'Auditoria externa identificou gaps na política atual. Atualização requerida pelo Conselho.',
    decisao_solicitada: 'Aprovar nova versão da Política de Compliance Anticorrupção (v4.0).',
    comite_id: COMITES[5].id,
    comite_nome: COMITES[5].nome,
    comite_cor: COMITES[5].cor,
    responsavel_nome: RESPONSAVEIS[2].nome,
    responsavel_email: RESPONSAVEIS[2].email,
    status: 'aguardando_ata',
    prioridade: 'alta',
    risco: 'alto',
    sla_status: 'on_track',
    sla_deadline: '2026-05-15T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 5,
    votos_favor: 5,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Redação da ata pelo secretário até 10/05',
    pareceres: [],
    evidencias: [
      {
        id: 'e-004',
        nome: 'Política Compliance v4.0.pdf',
        url: '#',
        tipo: 'documento',
        uploaded_by: 'Beatriz Mendes',
        created_at: '2026-04-20T10:00:00Z',
      },
    ],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-006',
        acao: 'Votação concluída',
        descricao: 'Aprovado por unanimidade (5/5)',
        usuario_nome: 'Sistema',
        timestamp: '2026-05-04T16:00:00Z',
      },
      {
        id: 'a-007',
        acao: 'Aguardando ata',
        descricao: 'Encaminhado ao secretário para lavratura',
        usuario_nome: 'Sistema',
        timestamp: '2026-05-04T16:05:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-04-20T10:00:00Z',
    updated_at: '2026-05-04T16:05:00Z',
  },
  {
    id: 'dlb-004',
    titulo: 'Plano de Resposta a Incidente de Segurança Cibernética',
    descricao:
      'Implementação de novo SOC e protocolos de resposta a incidentes após exercício de simulação.',
    contexto: 'Resultado do tabletop exercise identificou tempo de resposta acima do aceitável.',
    decisao_solicitada: 'Aprovar contratação de SOC 24x7 e protocolos atualizados.',
    comite_id: COMITES[4].id,
    comite_nome: COMITES[4].nome,
    comite_cor: COMITES[4].cor,
    responsavel_nome: RESPONSAVEIS[3].nome,
    responsavel_email: RESPONSAVEIS[3].email,
    status: 'em_execucao',
    prioridade: 'critica',
    risco: 'critico',
    sla_status: 'overdue',
    sla_deadline: '2026-04-30T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 5,
    votos_favor: 5,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Implementação em atraso — escalação ao CEO',
    pareceres: [],
    evidencias: [
      {
        id: 'e-005',
        nome: 'Relatório Tabletop Exercise Q1.pdf',
        url: '#',
        tipo: 'relatorio',
        uploaded_by: 'Lucas Oliveira',
        created_at: '2026-03-15T10:00:00Z',
      },
    ],
    acoes_execucao: [
      {
        id: 'ax-001',
        titulo: 'Contratação do fornecedor SOC',
        responsavel_nome: 'Lucas Oliveira',
        prazo: '2026-04-15T00:00:00Z',
        status: 'concluida',
      },
      {
        id: 'ax-002',
        titulo: 'Onboarding e configuração do SOC',
        responsavel_nome: 'Lucas Oliveira',
        prazo: '2026-04-30T00:00:00Z',
        status: 'em_andamento',
      },
      {
        id: 'ax-003',
        titulo: 'Treinamento da equipe de TI',
        responsavel_nome: 'Ana Paula Reis',
        prazo: '2026-05-15T00:00:00Z',
        status: 'pendente',
      },
    ],
    audit_trail: [
      {
        id: 'a-008',
        acao: 'Aprovado',
        descricao: 'Aprovado pelo Comitê de Riscos',
        usuario_nome: 'Sistema',
        timestamp: '2026-04-01T10:00:00Z',
      },
      {
        id: 'a-009',
        acao: 'Execução iniciada',
        descricao: 'Plano de execução aprovado',
        usuario_nome: 'Lucas Oliveira',
        timestamp: '2026-04-05T09:00:00Z',
      },
    ],
    itens_relacionados: [
      { id: 'r-022', label: 'Risco cibersegurança', tipo: 'risco', href: '/riscos/r-022' },
    ],
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-04-30T18:00:00Z',
  },
  {
    id: 'dlb-005',
    titulo: 'Revisão de Limites de Alçada Financeira',
    descricao: 'Revisão dos limites de aprovação para gastos operacionais e estratégicos.',
    contexto: 'Estrutura organizacional foi modificada após aquisição da subsidiária Norte.',
    decisao_solicitada: 'Aprovar nova matriz de alçadas financeiras.',
    comite_id: COMITES[1].id,
    comite_nome: COMITES[1].nome,
    comite_cor: COMITES[1].cor,
    responsavel_nome: RESPONSAVEIS[4].nome,
    responsavel_email: RESPONSAVEIS[4].email,
    status: 'rascunho',
    prioridade: 'media',
    risco: 'medio',
    sla_status: 'on_track',
    sla_deadline: '2026-05-30T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 0,
    votos_favor: 0,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Finalizar minuta e submeter à revisão',
    pareceres: [],
    evidencias: [],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-010',
        acao: 'Rascunho criado',
        descricao: 'Iniciada redação da deliberação',
        usuario_nome: 'Ana Paula Reis',
        timestamp: '2026-05-03T14:00:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-05-03T14:00:00Z',
    updated_at: '2026-05-03T14:00:00Z',
  },
  {
    id: 'dlb-006',
    titulo: 'Dividendos Extraordinários Q1 2026',
    descricao: 'Distribuição de dividendos extraordinários referentes a resultado acima do esperado em Q1.',
    contexto: 'EBITDA Q1 superou guidance em 22%. Caixa robusto permite distribuição extraordinária.',
    decisao_solicitada: 'Aprovar distribuição de R$ 18M em dividendos extraordinários.',
    comite_id: COMITES[0].id,
    comite_nome: COMITES[0].nome,
    comite_cor: COMITES[0].cor,
    responsavel_nome: RESPONSAVEIS[5].nome,
    responsavel_email: RESPONSAVEIS[5].email,
    status: 'concluida',
    prioridade: 'media',
    risco: 'baixo',
    sla_status: 'on_track',
    sla_deadline: '2026-04-25T18:00:00Z',
    quorum_necessario: 7,
    quorum_atual: 7,
    votos_favor: 7,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Concluída — ata publicada',
    pareceres: [],
    evidencias: [],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-011',
        acao: 'Concluída',
        descricao: 'Deliberação encerrada com ata publicada',
        usuario_nome: 'Sistema',
        timestamp: '2026-04-28T10:00:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-04-10T10:00:00Z',
    updated_at: '2026-04-28T10:00:00Z',
  },
  {
    id: 'dlb-007',
    titulo: 'Auditoria Externa — Seleção PwC vs Deloitte',
    descricao: 'Seleção de auditoria externa para próximo ciclo de 3 anos.',
    contexto: 'Contrato atual com KPMG vence em 2026. Necessária rotação por exigência regulatória.',
    decisao_solicitada: 'Selecionar entre proposta da PwC (R$ 2.8M/ano) e Deloitte (R$ 2.4M/ano).',
    comite_id: COMITES[2].id,
    comite_nome: COMITES[2].nome,
    comite_cor: COMITES[2].cor,
    responsavel_nome: RESPONSAVEIS[2].nome,
    responsavel_email: RESPONSAVEIS[2].email,
    status: 'em_revisao',
    prioridade: 'alta',
    risco: 'medio',
    sla_status: 'at_risk',
    sla_deadline: '2026-05-12T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 0,
    votos_favor: 0,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Apresentação das duas propostas em 09/05',
    pareceres: [
      {
        id: 'p-005',
        autor_nome: 'CFO Ricardo Lima',
        tipo: 'financeiro',
        conteudo: 'Diferença de R$ 1.2M no triênio. Análise de qualidade técnica é fator decisivo.',
        status: 'com_ressalvas',
        created_at: '2026-05-01T15:00:00Z',
      },
    ],
    evidencias: [
      {
        id: 'e-006',
        nome: 'Proposta PwC.pdf',
        url: '#',
        tipo: 'documento',
        uploaded_by: 'Beatriz Mendes',
        created_at: '2026-04-25T10:00:00Z',
      },
      {
        id: 'e-007',
        nome: 'Proposta Deloitte.pdf',
        url: '#',
        tipo: 'documento',
        uploaded_by: 'Beatriz Mendes',
        created_at: '2026-04-25T10:30:00Z',
      },
    ],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-012',
        acao: 'Deliberação criada',
        descricao: 'Submetida ao Comitê de Auditoria',
        usuario_nome: 'Beatriz Mendes',
        timestamp: '2026-04-25T10:00:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-04-25T10:00:00Z',
    updated_at: '2026-05-01T15:00:00Z',
  },
  {
    id: 'dlb-008',
    titulo: 'Aquisição de Participação — Solar Tech S.A.',
    descricao: 'Aquisição de 35% de participação na Solar Tech, expandindo portfolio de geração distribuída.',
    contexto: 'Movimento estratégico para reduzir exposição a fontes não renováveis.',
    decisao_solicitada: 'Aprovar aquisição de R$ 95M para 35% de participação.',
    comite_id: COMITES[3].id,
    comite_nome: COMITES[3].nome,
    comite_cor: COMITES[3].cor,
    responsavel_nome: RESPONSAVEIS[0].nome,
    responsavel_email: RESPONSAVEIS[0].email,
    status: 'em_votacao',
    prioridade: 'critica',
    risco: 'alto',
    sla_status: 'on_track',
    sla_deadline: '2026-05-18T18:00:00Z',
    quorum_necessario: 7,
    quorum_atual: 4,
    votos_favor: 3,
    votos_contra: 0,
    votos_abstencao: 1,
    proxima_acao: 'Aguardando 3 votos remanescentes',
    pareceres: [
      {
        id: 'p-006',
        autor_nome: 'CFO Ricardo Lima',
        tipo: 'financeiro',
        conteudo: 'TIR projetada 14.2%. Sinergias estimadas em R$ 8M/ano.',
        status: 'favoravel',
        created_at: '2026-05-01T10:00:00Z',
      },
    ],
    evidencias: [
      {
        id: 'e-008',
        nome: 'Due Diligence Solar Tech.pdf',
        url: '#',
        tipo: 'relatorio',
        uploaded_by: 'Marina Costa',
        created_at: '2026-04-22T10:00:00Z',
      },
    ],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-013',
        acao: 'Deliberação criada',
        descricao: 'Submetida ao Comitê Estratégico',
        usuario_nome: 'Marina Costa',
        timestamp: '2026-04-22T10:00:00Z',
      },
    ],
    itens_relacionados: [
      { id: 'pj-301', label: 'Projeto M&A Solar Tech', tipo: 'projeto', href: '/projetos/pj-301' },
    ],
    created_at: '2026-04-22T10:00:00Z',
    updated_at: '2026-05-03T16:00:00Z',
  },
  {
    id: 'dlb-009',
    titulo: 'Ajuste no Modelo de Remuneração Variável',
    descricao: 'Revisão dos KPIs de bônus de diretoria executiva para 2026.',
    contexto: 'Comitê de Pessoas recomendou maior peso para indicadores ESG.',
    decisao_solicitada: 'Aprovar nova matriz de KPIs com 25% atrelados a ESG.',
    comite_id: COMITES[0].id,
    comite_nome: COMITES[0].nome,
    comite_cor: COMITES[0].cor,
    responsavel_nome: RESPONSAVEIS[4].nome,
    responsavel_email: RESPONSAVEIS[4].email,
    status: 'rascunho',
    prioridade: 'baixa',
    risco: 'baixo',
    sla_status: 'on_track',
    sla_deadline: '2026-06-15T18:00:00Z',
    quorum_necessario: 7,
    quorum_atual: 0,
    votos_favor: 0,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Refinar proposta com RH',
    pareceres: [],
    evidencias: [],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-014',
        acao: 'Rascunho criado',
        descricao: 'Iniciada elaboração',
        usuario_nome: 'Ana Paula Reis',
        timestamp: '2026-05-04T11:00:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-05-04T11:00:00Z',
    updated_at: '2026-05-04T11:00:00Z',
  },
  {
    id: 'dlb-010',
    titulo: 'Reestruturação Dívida — Emissão Debêntures',
    descricao: 'Captação de R$ 250M via debêntures para alongamento do perfil da dívida.',
    contexto: 'Janela de mercado favorável. Custo médio atual da dívida pode ser reduzido em 180bps.',
    decisao_solicitada: 'Aprovar emissão de debêntures de R$ 250M, prazo 7 anos.',
    comite_id: COMITES[1].id,
    comite_nome: COMITES[1].nome,
    comite_cor: COMITES[1].cor,
    responsavel_nome: RESPONSAVEIS[5].nome,
    responsavel_email: RESPONSAVEIS[5].email,
    status: 'em_execucao',
    prioridade: 'alta',
    risco: 'medio',
    sla_status: 'at_risk',
    sla_deadline: '2026-05-10T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 5,
    votos_favor: 5,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Coordenadores em roadshow — book building em 09/05',
    pareceres: [],
    evidencias: [],
    acoes_execucao: [
      {
        id: 'ax-004',
        titulo: 'Selecionar coordenadores',
        responsavel_nome: 'Felipe Tavares',
        prazo: '2026-04-20T00:00:00Z',
        status: 'concluida',
      },
      {
        id: 'ax-005',
        titulo: 'Roadshow institucional',
        responsavel_nome: 'Felipe Tavares',
        prazo: '2026-05-09T00:00:00Z',
        status: 'em_andamento',
      },
      {
        id: 'ax-006',
        titulo: 'Book building e precificação',
        responsavel_nome: 'Felipe Tavares',
        prazo: '2026-05-12T00:00:00Z',
        status: 'pendente',
      },
    ],
    audit_trail: [
      {
        id: 'a-015',
        acao: 'Aprovada',
        descricao: 'Aprovada pelo Comitê Financeiro',
        usuario_nome: 'Sistema',
        timestamp: '2026-04-15T10:00:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-04-10T10:00:00Z',
    updated_at: '2026-05-04T18:00:00Z',
  },
  {
    id: 'dlb-011',
    titulo: 'Política de Diversidade e Inclusão 2026',
    descricao: 'Aprovação das metas e iniciativas de D&I para 2026.',
    contexto: 'Continuidade do programa lançado em 2024.',
    decisao_solicitada: 'Aprovar metas: 40% mulheres em liderança até 2027.',
    comite_id: COMITES[5].id,
    comite_nome: COMITES[5].nome,
    comite_cor: COMITES[5].cor,
    responsavel_nome: RESPONSAVEIS[2].nome,
    responsavel_email: RESPONSAVEIS[2].email,
    status: 'concluida',
    prioridade: 'media',
    risco: 'baixo',
    sla_status: 'on_track',
    sla_deadline: '2026-04-30T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 5,
    votos_favor: 5,
    votos_contra: 0,
    votos_abstencao: 0,
    proxima_acao: 'Concluída',
    pareceres: [],
    evidencias: [],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-016',
        acao: 'Concluída',
        descricao: 'Política publicada',
        usuario_nome: 'Sistema',
        timestamp: '2026-04-29T10:00:00Z',
      },
    ],
    itens_relacionados: [],
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-04-29T10:00:00Z',
  },
  {
    id: 'dlb-012',
    titulo: 'Reforço de Provisão Trabalhista — Litígio Sindical',
    descricao: 'Aumento de provisão para litígio sindical em curso após nova decisão de 1ª instância.',
    contexto: 'Sentença desfavorável aumentou exposição estimada para R$ 14M.',
    decisao_solicitada: 'Aprovar reforço de provisão de R$ 8M.',
    comite_id: COMITES[2].id,
    comite_nome: COMITES[2].nome,
    comite_cor: COMITES[2].cor,
    responsavel_nome: RESPONSAVEIS[3].nome,
    responsavel_email: RESPONSAVEIS[3].email,
    status: 'em_votacao',
    prioridade: 'alta',
    risco: 'alto',
    sla_status: 'overdue',
    sla_deadline: '2026-05-02T18:00:00Z',
    quorum_necessario: 5,
    quorum_atual: 3,
    votos_favor: 2,
    votos_contra: 1,
    votos_abstencao: 0,
    proxima_acao: 'Atrasada — escalação ao Conselho',
    pareceres: [
      {
        id: 'p-007',
        autor_nome: 'Dr. Carlos Eduardo',
        tipo: 'juridico',
        conteudo: 'Provisão consistente com expectativa de perda provável.',
        status: 'favoravel',
        created_at: '2026-04-28T10:00:00Z',
      },
    ],
    evidencias: [],
    acoes_execucao: [],
    audit_trail: [
      {
        id: 'a-017',
        acao: 'Votação iniciada',
        descricao: 'Período de votação aberto',
        usuario_nome: 'Sistema',
        timestamp: '2026-04-28T10:00:00Z',
      },
    ],
    itens_relacionados: [
      { id: 'r-077', label: 'Risco trabalhista sindical', tipo: 'risco', href: '/riscos/r-077' },
    ],
    created_at: '2026-04-26T10:00:00Z',
    updated_at: '2026-05-04T10:00:00Z',
  },
];

/**
 * Ata real: flag do modelo live (`minutes` JSONB via adapter) ou evento de
 * ata/minutes na trilha de auditoria. Não presume ata em toda concluída —
 * no live, decisões rejeitadas resolvem sem passar por awaiting_minutes.
 */
export function hasAta(d: Deliberacao): boolean {
  return (
    d.tem_ata === true ||
    d.audit_trail.some((ev) =>
      /\bata\b|minutes_(generated|published)/i.test(`${ev.acao} ${ev.descricao}`),
    )
  );
}

/**
 * Revisão FORMAL: status atual de revisão, ou o flag derivado no live-adapter
 * (histórico de status / parecer anterior à votação). Um parecer opcional
 * solicitado durante a votação NÃO insere etapa de revisão. O fallback por
 * pareceres só vale para o mock, que não tem histórico de status: conta
 * apenas pareceres emitidos antes do evento "Votação iniciada" da trilha.
 */
export function hasFormalReviewStep(d: Deliberacao): boolean {
  if (d.status === 'em_revisao') return true;
  if (d.revisao_formal !== undefined) return d.revisao_formal;
  const votacaoInicio = d.audit_trail.find((ev) => /vota[çc][ãa]o iniciada/i.test(ev.acao))?.timestamp;
  if (votacaoInicio) {
    return d.pareceres.some((p) => p.created_at <= votacaoInicio);
  }
  return d.pareceres.length > 0;
}

export function countByStatus(items: Deliberacao[], status: DeliberacaoStatus): number {
  return items.filter((d) => d.status === status).length;
}

export function countBySla(items: Deliberacao[], sla: SlaStatus): number {
  return items.filter((d) => d.sla_status === sla).length;
}

export function getOpenCount(items: Deliberacao[]): number {
  return items.filter((d) => d.status !== 'concluida').length;
}

export function getCriticalCount(items: Deliberacao[]): number {
  return items.filter(
    (d) => d.prioridade === 'critica' || d.risco === 'critico',
  ).length;
}
