/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/sync-contracts-from-excel.mjs
// Source: /Users/schutzer/Desktop/Contratos em Andamento_ Recebimentos - Insight Energy.xlsx
// Sheet: ACOMPANHAMENTO - OS
// Headers: A=OP | B=Ordem de Serviço | C=Cliente | D=Local | E=Início | F=Prazo | G=Status | H=ART | I=Relatório | J=Valor Total | K=Faturado | L=A faturar | M=Observação | N=13

import type { Contract } from '@/lib/types';

export const EXCEL_SYNC_META = {
  sourcePath: "/Users/schutzer/Desktop/Contratos em Andamento_ Recebimentos - Insight Energy.xlsx",
  sheetName: "ACOMPANHAMENTO - OS",
  synchronizedAt: "2026-02-28T03:02:37.598Z",
  totalRowsSynchronized: 38,
} as const;

export const excelContracts: Contract[] = [
  { id: "excel-2-152277-0", name: "OS 152277.0 - ENEL - GUARDA CHUVA", vendorOrParty: "ENEL", value: 31830450.6, currency: 'BRL', signingDate: new Date("2024-03-04T00:00:00.000Z"), expirationDate: new Date("2026-03-05T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "expiring_soon", uploadedAt: new Date("2024-03-04T00:00:00.000Z") },
  { id: "excel-3-1286-06", name: "OS 1286.06 - ELETRONORTE - HH", vendorOrParty: "ELETRONORTE", value: 650000, currency: 'BRL', signingDate: new Date("2020-07-20T00:00:00.000Z"), expirationDate: new Date("2026-02-28T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "expiring_soon", uploadedAt: new Date("2020-07-20T00:00:00.000Z"), notes: "Medição de dezembro enviada" },
  { id: "excel-4-201067-0", name: "OS 201067.0 - CEMIG - SALTO GRANDE", vendorOrParty: "CEMIG", value: 181818525.9, currency: 'BRL', signingDate: new Date("2024-07-01T00:00:00.000Z"), expirationDate: new Date("2027-11-13T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "active", uploadedAt: new Date("2024-07-01T00:00:00.000Z") },
  { id: "excel-5-350604-0", name: "OS 350604.0 - PETROBRAS - LICITAÇÃO", vendorOrParty: "PETROBRAS", value: 74467067.82, currency: 'BRL', fileUrl: '', riskClassification: "high", status: "active", uploadedAt: new Date("2026-02-27T00:00:00.000Z"), notes: "Aguardando kick off para definições" },
  { id: "excel-6-271802-0", name: "OS 271802.0 - ELETROBRAS - UHE BAGUARI", vendorOrParty: "ELETROBRAS", value: 239900, currency: 'BRL', signingDate: new Date("2025-09-03T00:00:00.000Z"), expirationDate: new Date("2025-12-01T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-09-03T00:00:00.000Z"), notes: "Carregou dia 19/12" },
  { id: "excel-7-292773-0", name: "OS 292773.0 - COPEL - UHE MAUÁ", vendorOrParty: "COPEL", value: 137944.8, currency: 'BRL', signingDate: new Date("2025-08-04T00:00:00.000Z"), expirationDate: new Date("2025-12-02T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-08-04T00:00:00.000Z"), notes: "BM enviado 02/12, pendente relatório" },
  { id: "excel-8-294142-0", name: "OS 294142.0 - PETROBRAS - TMA", vendorOrParty: "PETROBRAS", value: 53155567.31, currency: 'BRL', signingDate: new Date("2025-10-20T00:00:00.000Z"), expirationDate: new Date("2029-10-18T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "active", uploadedAt: new Date("2025-10-20T00:00:00.000Z"), notes: "Mobiliza 14/01 até 04/02 - em andamento, equipe em campo" },
  { id: "excel-9-291221-0", name: "OS 291221.0 - ELETROBRAS - CAVITAÇÃO", vendorOrParty: "ELETROBRAS", value: 15210890.8, currency: 'BRL', signingDate: new Date("2025-11-12T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "active", uploadedAt: new Date("2025-11-12T00:00:00.000Z"), notes: "Inicia os serviços dia 19/01 Mascarena UG18 (postergado para fevereiro) e furnas UG05" },
  { id: "excel-10-299652-0", name: "OS 299652.0 - CELESC - PCH GARCIA", vendorOrParty: "CELESC", value: 665800, currency: 'BRL', signingDate: new Date("2025-07-22T00:00:00.000Z"), expirationDate: new Date("2025-12-19T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-07-22T00:00:00.000Z"), notes: "Finalizado, aguardando relatório para enviar ao cliente" },
  { id: "excel-11-339252-0", name: "OP 339252.0 - AXIA ENERGIA", vendorOrParty: "AXIA ENERGIA", value: 49, currency: 'BRL', signingDate: new Date("2026-03-23T00:00:00.000Z"), expirationDate: new Date("2026-10-01T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "active", uploadedAt: new Date("2026-03-23T00:00:00.000Z") },
  { id: "excel-12-324581-0", name: "OS 324581.0 - BELEM BIOENERGIA", vendorOrParty: "BELEM BIOENERGIA", value: 1395676.8, currency: 'BRL', signingDate: new Date("2025-11-05T00:00:00.000Z"), expirationDate: new Date("2026-06-03T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "active", uploadedAt: new Date("2025-11-05T00:00:00.000Z"), notes: "Engenharia ainda não passou a lista de materiais para o PCP, pendente projeto executivo também" },
  { id: "excel-13-214612-0", name: "OS 214612.0 - KLABIN - TELÊMACO", vendorOrParty: "KLABIN", value: 950000, currency: 'BRL', signingDate: new Date("2025-09-15T00:00:00.000Z"), expirationDate: new Date("2025-12-15T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "expired", uploadedAt: new Date("2025-09-15T00:00:00.000Z"), notes: "Aguardando definição do cliente" },
  { id: "excel-14-2774-08", name: "OS 2774.08 - ENEL - CACHOEIRA DOURADA", vendorOrParty: "ENEL", value: 8032339.76, currency: 'BRL', signingDate: new Date("2025-10-20T00:00:00.000Z"), expirationDate: new Date("2026-05-06T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "expiring_soon", uploadedAt: new Date("2025-10-20T00:00:00.000Z"), notes: "Aguardando materiais para o campo, pendente pagamento dos condutores" },
  { id: "excel-15-295968-0", name: "OS 295968.0 - ELETRONORTE - UGH 18", vendorOrParty: "ELETRONORTE", value: 14290397.53, currency: 'BRL', signingDate: new Date("2025-10-17T00:00:00.000Z"), expirationDate: new Date("2026-03-12T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "expiring_soon", uploadedAt: new Date("2025-10-17T00:00:00.000Z"), notes: "Verificar com equipe de Tucuruí" },
  { id: "excel-16-200337-0", name: "OS 200337.0 - ENEL - PCH QUATIARA", vendorOrParty: "ENEL", value: 4355415.92, currency: 'BRL', signingDate: new Date("2025-01-06T00:00:00.000Z"), expirationDate: new Date("2026-03-13T00:00:00.000Z"), fileUrl: '', riskClassification: "medium", status: "expiring_soon", uploadedAt: new Date("2025-01-06T00:00:00.000Z"), notes: "Finalizada parte da fábrica, falta chegar peças na usina para montagem" },
  { id: "excel-17-330059-0", name: "OS 330059.0 - ENEL - PCH MOURÃO", vendorOrParty: "ENEL", value: 548000, currency: 'BRL', signingDate: new Date("2025-10-06T00:00:00.000Z"), expirationDate: new Date("2025-12-19T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-10-06T00:00:00.000Z"), notes: "Carregamento 12/01" },
  { id: "excel-18-290490-0", name: "OS 290490.0 - ARCELORMITTAL", vendorOrParty: "ARCELORMITTAL", value: 222109.24, currency: 'BRL', signingDate: new Date("2025-05-07T00:00:00.000Z"), expirationDate: new Date("2026-02-05T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "expired", uploadedAt: new Date("2025-05-07T00:00:00.000Z"), notes: "Aguardando confirmação da data de coleta pelo cliente" },
  { id: "excel-19-290856-0", name: "OS 290856.0 - ARCELORMITTAL", vendorOrParty: "ARCELORMITTAL", value: 254607.45, currency: 'BRL', signingDate: new Date("2025-05-13T00:00:00.000Z"), expirationDate: new Date("2026-02-05T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "expired", uploadedAt: new Date("2025-05-13T00:00:00.000Z"), notes: "Aguardando confirmação da data de coleta pelo cliente" },
  { id: "excel-20-235157-0", name: "OS 235157.0 - KLABIN - OTACÍLIO", vendorOrParty: "KLABIN", value: 1200000, currency: 'BRL', signingDate: new Date("2025-01-09T00:00:00.000Z"), expirationDate: new Date("2025-04-09T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-01-09T00:00:00.000Z"), notes: "Carregamento para 12/01" },
  { id: "excel-21-336664-0", name: "OS 336664.0 - AMBAR - SALTO MORAES", vendorOrParty: "AMBAR", value: 883317.21, currency: 'BRL', signingDate: new Date("2025-10-16T00:00:00.000Z"), expirationDate: new Date("2026-01-23T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-10-16T00:00:00.000Z"), notes: "Serviço finalizado, pendente enviar data book" },
  { id: "excel-22-343635-0", name: "OS 343635.0 - POSITIVO", vendorOrParty: "POSITIVO", value: 0, currency: 'BRL', signingDate: new Date("2026-01-09T00:00:00.000Z"), expirationDate: new Date("2026-01-23T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "expired", uploadedAt: new Date("2026-01-09T00:00:00.000Z"), notes: "Cliente cancelou a fabricação dos VBlocks" },
  { id: "excel-23-334472-0", name: "OS 334472.0 - ENEL - PCH QUATIARA", vendorOrParty: "ENEL", value: 136484.97, currency: 'BRL', signingDate: new Date("2025-12-03T00:00:00.000Z"), expirationDate: new Date("2025-12-24T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-12-03T00:00:00.000Z"), notes: "Coleta programada para 29/12" },
  { id: "excel-24-304400-0", name: "OS 304400.0 - UMOE", vendorOrParty: "UMOE", value: 188887.5, currency: 'BRL', signingDate: new Date("2026-01-05T00:00:00.000Z"), expirationDate: new Date("2026-02-10T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-01-05T00:00:00.000Z"), notes: "Atividades dentro do prazo" },
  { id: "excel-25-345461-0", name: "OS 345461.0 - ENEVA", vendorOrParty: "ENEVA", value: 2490000, currency: 'BRL', signingDate: new Date("2025-11-24T00:00:00.000Z"), expirationDate: new Date("2025-11-19T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-11-24T00:00:00.000Z"), notes: "Finalizado primeira parte" },
  { id: "excel-26-352431-0", name: "OP 352431.0 - ENEVA", vendorOrParty: "ENEVA", value: 87, currency: 'BRL', signingDate: new Date("2025-11-21T00:00:00.000Z"), expirationDate: new Date("2026-02-19T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-11-21T00:00:00.000Z") },
  { id: "excel-27-272167-0", name: "OS 272167.0 - POWER BUS", vendorOrParty: "POWER BUS", value: 1427402.78, currency: 'BRL', signingDate: new Date("2025-08-07T00:00:00.000Z"), expirationDate: new Date("2025-12-19T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-08-07T00:00:00.000Z"), notes: "Será feito um novo orçaemento para a finalização dos serviços" },
  { id: "excel-28-338490-0", name: "OS 338490.0 - GE VERNOVA - HH", vendorOrParty: "GE VERNOVA", value: 200415.6, currency: 'BRL', signingDate: new Date("2025-11-18T00:00:00.000Z"), expirationDate: new Date("2025-12-12T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-11-18T00:00:00.000Z"), notes: "Finalizado 11/12" },
  { id: "excel-29-320532-0", name: "OS 320532.0 - SIDEWINDERS", vendorOrParty: "SIDEWINDERS", value: 0, currency: 'BRL', signingDate: new Date("2025-11-25T00:00:00.000Z"), expirationDate: new Date("2025-12-11T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-11-25T00:00:00.000Z") },
  { id: "excel-30-338125-0", name: "OP 338125.0 - AMBAR - LAGES", vendorOrParty: "AMBAR", value: 52669.68, currency: 'BRL', signingDate: new Date("2025-12-22T00:00:00.000Z"), expirationDate: new Date("2025-12-23T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-12-22T00:00:00.000Z") },
  { id: "excel-31-194432-0", name: "OP 194432.0 - KLABIN - TELÊMACO", vendorOrParty: "KLABIN", value: 96, currency: 'BRL', signingDate: new Date("2026-01-29T00:00:00.000Z"), expirationDate: new Date("2026-02-02T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-01-29T00:00:00.000Z") },
  { id: "excel-32-356845-0", name: "OP 356845.0 - BELEM BIOENERGIA", vendorOrParty: "BELEM BIOENERGIA", value: 98, currency: 'BRL', signingDate: new Date("2026-01-07T00:00:00.000Z"), expirationDate: new Date("2026-01-11T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-01-07T00:00:00.000Z") },
  { id: "excel-33-357210-0", name: "OP 357210.0 - POWER BUS", vendorOrParty: "POWER BUS", value: 99, currency: 'BRL', signingDate: new Date("2025-12-06T00:00:00.000Z"), expirationDate: new Date("2026-01-10T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2025-12-06T00:00:00.000Z") },
  { id: "excel-34-359767-0", name: "OP 359767.0 - ENEL - CULUENE", vendorOrParty: "ENEL", value: 87, currency: 'BRL', signingDate: new Date("2026-01-20T00:00:00.000Z"), expirationDate: new Date("2026-01-30T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-01-20T00:00:00.000Z") },
  { id: "excel-35-360497-0", name: "OP 360497.0 - CPFL - MONTE CLARO", vendorOrParty: "CPFL", value: 102, currency: 'BRL', signingDate: new Date("2026-01-20T00:00:00.000Z"), expirationDate: new Date("2026-01-23T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-01-20T00:00:00.000Z") },
  { id: "excel-36-362689-0", name: "OP 362689.0 - NORTE ENERGIA - BELO MONTE", vendorOrParty: "NORTE ENERGIA", value: 0, currency: 'BRL', signingDate: new Date("2026-02-02T00:00:00.000Z"), expirationDate: new Date("2026-02-10T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "expired", uploadedAt: new Date("2026-02-02T00:00:00.000Z") },
  { id: "excel-37-368928-0", name: "OP 368928.0 - SUZANO", vendorOrParty: "SUZANO", value: 105, currency: 'BRL', signingDate: new Date("2026-02-21T00:00:00.000Z"), expirationDate: new Date("2026-02-25T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-02-21T00:00:00.000Z") },
  { id: "excel-38-369658-0", name: "OP 369658.0 - CPFL", vendorOrParty: "CPFL", value: 0, currency: 'BRL', signingDate: new Date("2026-02-23T00:00:00.000Z"), expirationDate: new Date("2026-02-24T00:00:00.000Z"), fileUrl: '', riskClassification: "low", status: "expired", uploadedAt: new Date("2026-02-23T00:00:00.000Z") },
  { id: "excel-39-370024-0", name: "OP 370024.0 - POSITIVO", vendorOrParty: "POSITIVO", value: 0, currency: 'BRL', signingDate: new Date("2026-03-27T00:00:00.000Z"), expirationDate: new Date("2026-03-03T00:00:00.000Z"), fileUrl: '', riskClassification: "high", status: "expiring_soon", uploadedAt: new Date("2026-03-27T00:00:00.000Z") }
];

export const excelPortfolioTotals = {
  totalContracted: 394804594.67,
  totalInvoiced: 17872682.33,
  backlogToInvoice: 376931912.34,
  totalContracts: 38,
};

export const excelCompanyBreakdown = [
  { company: "CEMIG", totalContracted: 181818525.9, backlogToInvoice: 181818499.9, contractsCount: 1 },
  { company: "PETROBRAS", totalContracted: 127622635.13, backlogToInvoice: 127622635.13, contractsCount: 2 },
  { company: "ENEL", totalContracted: 44902778.25, backlogToInvoice: 34961382.12, contractsCount: 6 },
  { company: "ELETROBRAS", totalContracted: 15450790.8, backlogToInvoice: 15450790.8, contractsCount: 2 },
  { company: "ELETRONORTE", totalContracted: 14940397.53, backlogToInvoice: 13266321.61, contractsCount: 2 },
  { company: "ENEVA", totalContracted: 2490087, backlogToInvoice: 87, contractsCount: 2 },
  { company: "KLABIN", totalContracted: 2150096, backlogToInvoice: 665096, contractsCount: 3 },
  { company: "POWER BUS", totalContracted: 1427501.78, backlogToInvoice: 99, contractsCount: 2 },
  { company: "BELEM BIOENERGIA", totalContracted: 1395774.8, backlogToInvoice: 1395774.8, contractsCount: 2 },
  { company: "AMBAR", totalContracted: 935986.89, backlogToInvoice: 935892.89, contractsCount: 2 },
  { company: "CELESC", totalContracted: 665800, backlogToInvoice: 0, contractsCount: 1 },
  { company: "ARCELORMITTAL", totalContracted: 476716.69, backlogToInvoice: 476716.69, contractsCount: 2 },
  { company: "GE VERNOVA", totalContracted: 200415.6, backlogToInvoice: 200415.6, contractsCount: 1 },
  { company: "UMOE", totalContracted: 188887.5, backlogToInvoice: 0, contractsCount: 1 },
  { company: "COPEL", totalContracted: 137944.8, backlogToInvoice: 137944.8, contractsCount: 1 },
  { company: "SUZANO", totalContracted: 105, backlogToInvoice: 105, contractsCount: 1 },
  { company: "CPFL", totalContracted: 102, backlogToInvoice: 102, contractsCount: 2 },
  { company: "AXIA ENERGIA", totalContracted: 49, backlogToInvoice: 49, contractsCount: 1 },
  { company: "POSITIVO", totalContracted: 0, backlogToInvoice: 0, contractsCount: 2 },
  { company: "SIDEWINDERS", totalContracted: 0, backlogToInvoice: 0, contractsCount: 1 },
  { company: "NORTE ENERGIA", totalContracted: 0, backlogToInvoice: 0, contractsCount: 1 }
];
